<?php

/** Localized labels for the compendium editor. Article content is translated separately. */
function vfnCompendiumAdminTranslations(string $language): array
{
    $keys = ['compendium_manage','compendium_admin_title','compendium_admin_intro','compendium_new_article','compendium_open','compendium_field_title','compendium_field_slug','compendium_field_summary','compendium_field_content','compendium_field_category','compendium_field_language','compendium_field_scope','compendium_field_division','compendium_field_airport','compendium_field_status','compendium_field_sort','compendium_field_aliases','compendium_scope_global','compendium_scope_division','compendium_status_draft','compendium_status_published','compendium_status_archived','compendium_preview','compendium_revisions','compendium_restore','compendium_homepage'];
    $translations = [
        'ar' => ['إدارة الدليل','إدارة دليل VFN','إنشاء وإدارة المقالات العامة أو الخاصة بالأقسام وإعادة التوجيه والمراجعات. يُسمح بـ HTML وCSS الآمن، ويُحظر JavaScript.','مقال جديد','فتح الدليل','العنوان','العنوان المختصر','الملخص','محتوى HTML','الفئة','اللغة','النطاق','القسم','رمز المطار / الموقع','الحالة','ترتيب العرض','إعادة التوجيه / الأسماء البديلة','عالمي','القسم','مسودة','منشور','مؤرشف','معاينة','سجل المراجعات','استعادة','استخدام كصفحة رئيسية للدليل'],
        'bn' => ['সংকলন পরিচালনা','VFN সংকলন প্রশাসন','বৈশ্বিক বা বিভাগভিত্তিক নিবন্ধ, পুনর্নির্দেশ ও সংস্করণ তৈরি ও পরিচালনা করুন। নিরাপদ HTML ও CSS সমর্থিত; JavaScript নিষিদ্ধ।','নতুন নিবন্ধ','সংকলন খুলুন','শিরোনাম','ঠিকানা / স্লাগ','সারাংশ','HTML বিষয়বস্তু','বিভাগ','ভাষা','পরিধি','ডিভিশন','বিমানবন্দর / অবস্থান কোড','অবস্থা','সাজানোর ক্রম','পুনর্নির্দেশ / উপনাম','বিশ্বব্যাপী','ডিভিশন','খসড়া','প্রকাশিত','সংরক্ষিত','পূর্বরূপ','সংস্করণ ইতিহাস','পুনরুদ্ধার','সংকলনের প্রধান পৃষ্ঠা হিসেবে ব্যবহার করুন'],
        'zh' => ['管理手册','VFN 手册管理','创建和管理全局或分部文章、重定向及修订版本。支持安全的 HTML 和 CSS；禁止 JavaScript。','新建文章','打开手册','标题','地址 / Slug','摘要','HTML 内容','类别','语言','范围','分部','机场 / 地点代码','状态','排序顺序','重定向 / 别名','全局','分部','草稿','已发布','已归档','预览','修订历史','恢复','设为手册主页'],
        'nl' => ['Compendium beheren','VFN-compendiumbeheer','Maak en beheer globale of divisiegebonden artikelen, doorverwijzingen en revisies. Veilige HTML en CSS worden ondersteund; JavaScript is geblokkeerd.','Nieuw artikel','Compendium openen','Titel','Adres / slug','Samenvatting','HTML-inhoud','Categorie','Taal','Bereik','Divisie','Luchthaven- / locatiecode','Status','Sorteervolgorde','Doorverwijzingen / aliassen','Globaal','Divisie','Concept','Gepubliceerd','Gearchiveerd','Voorbeeld','Revisiegeschiedenis','Herstellen','Als startpagina van het compendium gebruiken'],
        'fr' => ['Gérer le compendium','Administration du compendium VFN','Créez et gérez des articles globaux ou propres aux divisions, des redirections et des révisions. Le HTML et le CSS sécurisés sont acceptés ; JavaScript est bloqué.','Nouvel article','Ouvrir le compendium','Titre','Adresse / slug','Résumé','Contenu HTML','Catégorie','Langue','Portée','Division','Code aéroport / lieu','Statut','Ordre de tri','Redirections / alias','Global','Division','Brouillon','Publié','Archivé','Aperçu','Historique des révisions','Restaurer','Utiliser comme page d’accueil du compendium'],
        'hi' => ['संग्रह प्रबंधित करें','VFN संग्रह प्रशासन','वैश्विक या डिवीजन-विशिष्ट लेख, पुनर्निर्देशन और संशोधन बनाएँ व प्रबंधित करें। सुरक्षित HTML और CSS समर्थित हैं; JavaScript अवरुद्ध है।','नया लेख','संग्रह खोलें','शीर्षक','पता / स्लग','सारांश','HTML सामग्री','श्रेणी','भाषा','दायरा','डिवीजन','हवाई अड्डा / स्थान कोड','स्थिति','क्रम','पुनर्निर्देशन / उपनाम','वैश्विक','डिवीजन','मसौदा','प्रकाशित','संग्रहीत','पूर्वावलोकन','संशोधन इतिहास','पुनर्स्थापित करें','संग्रह के मुख्य पृष्ठ के रूप में उपयोग करें'],
        'id' => ['Kelola kompendium','Administrasi kompendium VFN','Buat dan kelola artikel global atau khusus divisi, pengalihan, dan revisi. HTML dan CSS aman didukung; JavaScript diblokir.','Artikel baru','Buka kompendium','Judul','Alamat / slug','Ringkasan','Konten HTML','Kategori','Bahasa','Cakupan','Divisi','Kode bandara / lokasi','Status','Urutan','Pengalihan / alias','Global','Divisi','Draf','Diterbitkan','Diarsipkan','Pratinjau','Riwayat revisi','Pulihkan','Gunakan sebagai halaman utama kompendium'],
        'it' => ['Gestisci il compendio','Amministrazione del compendio VFN','Crea e gestisci articoli globali o di divisione, reindirizzamenti e revisioni. Sono supportati HTML e CSS sicuri; JavaScript è bloccato.','Nuovo articolo','Apri il compendio','Titolo','Indirizzo / slug','Riepilogo','Contenuto HTML','Categoria','Lingua','Ambito','Divisione','Codice aeroporto / località','Stato','Ordinamento','Reindirizzamenti / alias','Globale','Divisione','Bozza','Pubblicato','Archiviato','Anteprima','Cronologia revisioni','Ripristina','Usa come pagina iniziale del compendio'],
        'ja' => ['コンペンディウムを管理','VFN コンペンディウム管理','全体またはディビジョン固有の記事、リダイレクト、改訂履歴を作成・管理します。安全な HTML と CSS に対応し、JavaScript は禁止されています。','新しい記事','コンペンディウムを開く','タイトル','アドレス / スラッグ','概要','HTML コンテンツ','カテゴリー','言語','適用範囲','ディビジョン','空港 / 場所コード','状態','表示順','リダイレクト / 別名','全体','ディビジョン','下書き','公開済み','アーカイブ済み','プレビュー','改訂履歴','復元','コンペンディウムのホームページに設定'],
        'ko' => ['편람 관리','VFN 편람 관리','전체 또는 디비전별 문서, 리디렉션 및 개정판을 만들고 관리합니다. 안전한 HTML과 CSS를 지원하며 JavaScript는 차단됩니다.','새 문서','편람 열기','제목','주소 / 슬러그','요약','HTML 내용','분류','언어','범위','디비전','공항 / 위치 코드','상태','정렬 순서','리디렉션 / 별칭','전체','디비전','초안','게시됨','보관됨','미리보기','개정 이력','복원','편람 홈페이지로 사용'],
        'pl' => ['Zarządzaj kompendium','Administracja kompendium VFN','Twórz i zarządzaj artykułami globalnymi lub dywizyjnymi, przekierowaniami i wersjami. Bezpieczny HTML i CSS są obsługiwane; JavaScript jest blokowany.','Nowy artykuł','Otwórz kompendium','Tytuł','Adres / slug','Podsumowanie','Treść HTML','Kategoria','Język','Zakres','Dywizja','Kod lotniska / miejsca','Status','Kolejność','Przekierowania / aliasy','Globalny','Dywizja','Szkic','Opublikowany','Zarchiwizowany','Podgląd','Historia wersji','Przywróć','Użyj jako strony głównej kompendium'],
        'pt' => ['Gerir compêndio','Administração do compêndio VFN','Crie e gira artigos globais ou específicos de divisão, redirecionamentos e revisões. HTML e CSS seguros são suportados; JavaScript é bloqueado.','Novo artigo','Abrir compêndio','Título','Endereço / slug','Resumo','Conteúdo HTML','Categoria','Idioma','Âmbito','Divisão','Código do aeroporto / local','Estado','Ordem','Redirecionamentos / aliases','Global','Divisão','Rascunho','Publicado','Arquivado','Pré-visualização','Histórico de revisões','Restaurar','Usar como página inicial do compêndio'],
        'ru' => ['Управление справочником','Администрирование справочника VFN','Создавайте и редактируйте общие или дивизионные статьи, перенаправления и версии. Безопасные HTML и CSS поддерживаются; JavaScript запрещён.','Новая статья','Открыть справочник','Заголовок','Адрес / slug','Краткое описание','HTML-содержимое','Категория','Язык','Область','Дивизион','Код аэропорта / места','Статус','Порядок сортировки','Перенаправления / псевдонимы','Глобально','Дивизион','Черновик','Опубликовано','В архиве','Предпросмотр','История версий','Восстановить','Использовать как главную страницу справочника'],
        'es' => ['Gestionar compendio','Administración del compendio VFN','Crea y gestiona artículos globales o de división, redirecciones y revisiones. Se admiten HTML y CSS seguros; JavaScript está bloqueado.','Nuevo artículo','Abrir compendio','Título','Dirección / slug','Resumen','Contenido HTML','Categoría','Idioma','Ámbito','División','Código de aeropuerto / lugar','Estado','Orden','Redirecciones / alias','Global','División','Borrador','Publicado','Archivado','Vista previa','Historial de revisiones','Restaurar','Usar como página principal del compendio'],
        'tr' => ['Kılavuzu yönet','VFN kılavuz yönetimi','Genel veya divizyona özel makaleleri, yönlendirmeleri ve sürümleri oluşturup yönetin. Güvenli HTML ve CSS desteklenir; JavaScript engellenir.','Yeni makale','Kılavuzu aç','Başlık','Adres / slug','Özet','HTML içeriği','Kategori','Dil','Kapsam','Divizyon','Havalimanı / konum kodu','Durum','Sıralama','Yönlendirmeler / takma adlar','Genel','Divizyon','Taslak','Yayınlandı','Arşivlendi','Önizleme','Sürüm geçmişi','Geri yükle','Kılavuz ana sayfası olarak kullan'],
    ];
    if (!isset($translations[$language])) return [];
    $result = array_combine($keys, $translations[$language]) ?: [];

    $extraKeys = ['compendium_new_section','compendium_invalid','compendium_slug_exists','compendium_alias_exists','compendium_saved','compendium_deleted','compendium_restored','compendium_aliases_hint','compendium_delete_confirm','compendium_category_general','compendium_category_radio','compendium_category_plugin','compendium_category_atc','compendium_category_training','compendium_category_exam','compendium_category_airport','compendium_category_rules','compendium_category_procedures'];
    $extras = [
        'ar' => ['قسم جديد','يرجى التحقق من الحقول المطلوبة والصلاحيات.','عنوان هذه المقالة مستخدم بالفعل.','هذا الاسم البديل مرتبط بمقالة أخرى.','تم حفظ المقالة.','تم حذف المقالة.','تمت استعادة النسخة.','مصطلح واحد في كل سطر، مثل TA أو Transition Altitude','هل تريد حقاً حذف المقالة وسجل نسخها؟','عام','الاتصالات اللاسلكية','إضافة الطيار','عميل المراقبة الجوية','التدريب','التحضير للاختبار','المطارات','القواعد','الإجراءات'],
        'bn' => ['নতুন বিভাগ','প্রয়োজনীয় ক্ষেত্র ও অনুমতি যাচাই করুন।','এই নিবন্ধের ঠিকানা ইতিমধ্যে ব্যবহৃত হচ্ছে।','এই উপনামটি অন্য নিবন্ধে ব্যবহৃত হচ্ছে।','নিবন্ধ সংরক্ষিত হয়েছে।','নিবন্ধ মুছে ফেলা হয়েছে।','সংস্করণ পুনরুদ্ধার করা হয়েছে।','প্রতি লাইনে একটি শব্দ, যেমন TA বা Transition Altitude','নিবন্ধ ও সংস্করণ ইতিহাস সত্যিই মুছবেন?','সাধারণ','রেডিও যোগাযোগ','পাইলট প্লাগইন','ATC ক্লায়েন্ট','প্রশিক্ষণ','পরীক্ষার প্রস্তুতি','বিমানবন্দর','নিয়ম','পদ্ধতি'],
        'zh' => ['新建章节','请检查必填字段和权限。','该文章地址已被使用。','该别名已分配给其他文章。','文章已保存。','文章已删除。','版本已恢复。','每行一个词，例如 TA 或 Transition Altitude','确定删除文章及其版本历史吗？','常规','无线电通信','飞行员插件','ATC 客户端','培训','考试准备','机场','规则','程序'],
        'nl' => ['Nieuwe sectie','Controleer de verplichte velden en je rechten.','Dit artikeladres is al in gebruik.','Deze alias hoort al bij een ander artikel.','Artikel opgeslagen.','Artikel verwijderd.','Versie hersteld.','Eén begrip per regel, bijvoorbeeld TA of Transition Altitude','Artikel en revisiegeschiedenis echt verwijderen?','Algemeen','Radiocommunicatie','Pilootplug-in','ATC-client','Opleiding','Examenvoorbereiding','Luchthavens','Regels','Procedures'],
        'fr' => ['Nouvelle section','Vérifiez les champs obligatoires et vos autorisations.','Cette adresse d’article est déjà utilisée.','Cet alias appartient déjà à un autre article.','Article enregistré.','Article supprimé.','Version restaurée.','Un terme par ligne, par ex. TA ou Transition Altitude','Supprimer réellement l’article et son historique ?','Général','Radiocommunication','Plugin pilote','Client ATC','Formation','Préparation aux examens','Aéroports','Règles','Procédures'],
        'hi' => ['नया अनुभाग','आवश्यक फ़ील्ड और अनुमतियाँ जाँचें।','यह लेख पता पहले से उपयोग में है।','यह उपनाम किसी अन्य लेख को दिया गया है।','लेख सहेजा गया।','लेख हटाया गया।','संस्करण पुनर्स्थापित किया गया।','प्रति पंक्ति एक शब्द, जैसे TA या Transition Altitude','क्या लेख और संस्करण इतिहास सचमुच हटाएँ?','सामान्य','रेडियो संचार','पायलट प्लगइन','ATC क्लाइंट','प्रशिक्षण','परीक्षा की तैयारी','हवाई अड्डे','नियम','प्रक्रियाएँ'],
        'id' => ['Bagian baru','Periksa bidang wajib dan izin Anda.','Alamat artikel ini sudah digunakan.','Alias ini sudah digunakan artikel lain.','Artikel disimpan.','Artikel dihapus.','Versi dipulihkan.','Satu istilah per baris, misalnya TA atau Transition Altitude','Yakin menghapus artikel dan riwayat revisinya?','Umum','Komunikasi radio','Plugin pilot','Klien ATC','Pelatihan','Persiapan ujian','Bandara','Peraturan','Prosedur'],
        'it' => ['Nuova sezione','Controlla i campi obbligatori e le autorizzazioni.','Questo indirizzo è già in uso.','Questo alias appartiene già a un altro articolo.','Articolo salvato.','Articolo eliminato.','Versione ripristinata.','Un termine per riga, ad es. TA o Transition Altitude','Eliminare davvero articolo e cronologia revisioni?','Generale','Comunicazioni radio','Plugin pilota','Client ATC','Formazione','Preparazione agli esami','Aeroporti','Regole','Procedure'],
        'ja' => ['新しいセクション','必須項目と権限を確認してください。','この記事アドレスは既に使用されています。','この別名は別の記事に割り当てられています。','記事を保存しました。','記事を削除しました。','版を復元しました。','1行に1語（例：TA、Transition Altitude）','記事と改訂履歴を削除しますか？','一般','無線通信','パイロットプラグイン','ATCクライアント','訓練','試験対策','空港','規則','手順'],
        'ko' => ['새 섹션','필수 입력란과 권한을 확인하세요.','이 문서 주소는 이미 사용 중입니다.','이 별칭은 다른 문서에 할당되어 있습니다.','문서가 저장되었습니다.','문서가 삭제되었습니다.','버전이 복원되었습니다.','한 줄에 하나씩 입력하세요. 예: TA, Transition Altitude','문서와 개정 이력을 삭제하시겠습니까?','일반','무선 통신','파일럿 플러그인','ATC 클라이언트','교육','시험 준비','공항','규정','절차'],
        'pl' => ['Nowa sekcja','Sprawdź wymagane pola i uprawnienia.','Ten adres artykułu jest już używany.','Ten alias jest przypisany do innego artykułu.','Artykuł zapisano.','Artykuł usunięto.','Wersję przywrócono.','Jedno pojęcie w wierszu, np. TA lub Transition Altitude','Usunąć artykuł wraz z historią wersji?','Ogólne','Łączność radiowa','Wtyczka pilota','Klient ATC','Szkolenie','Przygotowanie do egzaminu','Lotniska','Przepisy','Procedury'],
        'pt' => ['Nova secção','Verifique os campos obrigatórios e as permissões.','Este endereço já está a ser utilizado.','Este alias pertence a outro artigo.','Artigo guardado.','Artigo eliminado.','Versão restaurada.','Um termo por linha, por ex. TA ou Transition Altitude','Eliminar realmente o artigo e o histórico?','Geral','Comunicação por rádio','Plugin do piloto','Cliente ATC','Formação','Preparação para exames','Aeroportos','Regras','Procedimentos'],
        'ru' => ['Новый раздел','Проверьте обязательные поля и права доступа.','Этот адрес статьи уже используется.','Этот псевдоним назначен другой статье.','Статья сохранена.','Статья удалена.','Версия восстановлена.','Один термин на строку, например TA или Transition Altitude','Удалить статью и всю историю версий?','Общее','Радиосвязь','Плагин пилота','Клиент УВД','Обучение','Подготовка к экзамену','Аэропорты','Правила','Процедуры'],
        'es' => ['Nueva sección','Comprueba los campos obligatorios y los permisos.','Esta dirección ya está en uso.','Este alias pertenece a otro artículo.','Artículo guardado.','Artículo eliminado.','Versión restaurada.','Un término por línea, p. ej. TA o Transition Altitude','¿Eliminar el artículo y su historial de revisiones?','General','Radiocomunicación','Plugin de piloto','Cliente ATC','Formación','Preparación de exámenes','Aeropuertos','Reglas','Procedimientos'],
        'tr' => ['Yeni bölüm','Zorunlu alanları ve yetkileri kontrol edin.','Bu makale adresi zaten kullanılıyor.','Bu takma ad başka bir makaleye atanmış.','Makale kaydedildi.','Makale silindi.','Sürüm geri yüklendi.','Her satıra bir terim, ör. TA veya Transition Altitude','Makale ve sürüm geçmişi gerçekten silinsin mi?','Genel','Telsiz iletişimi','Pilot eklentisi','ATC istemcisi','Eğitim','Sınav hazırlığı','Havalimanları','Kurallar','Prosedürler'],
    ];
    if (isset($extras[$language])) {
        $result = array_replace($result, array_combine($extraKeys, $extras[$language]) ?: []);
    }
    return $result;
}
