CREATE TABLE IF NOT EXISTS atc_training_aircraft (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    trainer_session_id BIGINT UNSIGNED NOT NULL,
    callsign VARCHAR(40) NOT NULL,
    aircraft_icao VARCHAR(12) NOT NULL DEFAULT 'A320',
    placement_type ENUM('runway','taxiway','gate','air') NOT NULL DEFAULT 'gate',
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(10,7) NOT NULL,
    altitude INT NOT NULL DEFAULT 0,
    heading SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    target_heading SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    airspeed SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    control_mode ENUM('manual','automatic') NOT NULL DEFAULT 'manual',
    motion_state VARCHAR(20) NOT NULL DEFAULT 'parked',
    target_airspeed SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    target_altitude INT NOT NULL DEFAULT 0,
    vertical_speed_fpm SMALLINT UNSIGNED NOT NULL DEFAULT 1000,
    last_motion_at DATETIME NULL,
    transponder_code VARCHAR(4) NOT NULL DEFAULT '7000',
    transponder_status ENUM('standby','on','ident') NOT NULL DEFAULT 'standby',
    com1_frequency VARCHAR(7) NOT NULL DEFAULT '122.800',
    com2_frequency VARCHAR(7) NOT NULL DEFAULT '122.800',
    flight_rules CHAR(1) NOT NULL DEFAULT 'I',
    flight_type VARCHAR(4) NOT NULL DEFAULT 'G',
    communication_mode VARCHAR(20) NOT NULL DEFAULT 'VOICE',
    departure_airport VARCHAR(14) NOT NULL DEFAULT 'ZZZZ',
    arrival_airport VARCHAR(14) NOT NULL DEFAULT 'ZZZZ',
    alternate1_airport VARCHAR(14) NOT NULL DEFAULT 'ZZZZ',
    alternate2_airport VARCHAR(14) NOT NULL DEFAULT 'ZZZZ',
    route_text TEXT NOT NULL,
    cruising_level VARCHAR(20) NOT NULL DEFAULT '',
    cruising_speed VARCHAR(20) NOT NULL DEFAULT '',
    remarks TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_atc_training_callsign (trainer_session_id,callsign),
    KEY idx_atc_training_session (trainer_session_id),
    CONSTRAINT fk_atc_training_session FOREIGN KEY (trainer_session_id)
        REFERENCES atc_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
