<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8'); header('Cache-Control: no-store');
require_once __DIR__.'/../includes/session_bootstrap.php'; startVfnWebSession();
require_once __DIR__.'/config.php'; require_once __DIR__.'/../includes/web_session.php'; require_once __DIR__.'/../includes/atc_schema.php'; require_once __DIR__.'/../includes/cpdlc_schema.php'; require_once __DIR__.'/../includes/hoppie_cpdlc.php';
function outCpdlc(array $d,int $s=200){http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{
 $pdo=new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4",$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
 if(empty($_SESSION['web_user_id'])||!validateVfnWebSession($pdo))outCpdlc(['success'=>false,'message'=>'login_required'],401);
 $s=$pdo->prepare("SELECT * FROM atc_sessions WHERE user_id=:uid AND session_token=:token AND is_active=1 AND last_seen_at>=DATE_SUB(NOW(),INTERVAL 5 MINUTE) LIMIT 1");
 $s->execute(['uid'=>(int)$_SESSION['web_user_id'],'token'=>(string)($_SESSION['atc_session_token']??'')]);$atc=$s->fetch(PDO::FETCH_ASSOC);if(!$atc)outCpdlc(['success'=>false,'message'=>'atc_session_inactive'],409);
 $station=strtoupper((string)$atc['station_code']);$callsign=strtoupper((string)$atc['callsign']);$hoppieStation=vfnHoppieAtcStation($station);$action=strtolower(trim((string)($_REQUEST['action']??'list')));
 vfnHoppieSyncStation($pdo,$hoppieStation,true);
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!(int)$atc['can_control']||((int)$atc['is_spectator']&&!(int)($atc['is_trainer']??0)))outCpdlc(['success'=>false,'message'=>'atc_control_session_required'],403);
  $id=(int)($_POST['connection_id']??0);
  $q=$pdo->prepare("SELECT * FROM cpdlc_connections WHERE id=:id AND (station_code=:station OR station_code=:hoppie OR station_code=:callsign OR controller_session_id=:sid) LIMIT 1");$q->execute(['id'=>$id,'station'=>$station,'hoppie'=>$hoppieStation,'callsign'=>$callsign,'sid'=>$atc['id']]);$c=$q->fetch(PDO::FETCH_ASSOC);if(!$c)outCpdlc(['success'=>false,'message'=>'cpdlc_connection_not_found'],404);
  if(in_array($action,['accept','reject'],true)){$state=$action==='accept'?'connected':'rejected';$pdo->prepare("UPDATE cpdlc_connections SET state=:state,controller_session_id=:sid,controller_user_id=:uid,connected_at=IF(:state2='connected',NOW(),NULL),closed_at=IF(:state3='rejected',NOW(),NULL),last_activity_at=NOW() WHERE id=:id AND state='requested'")->execute(['state'=>$state,'sid'=>$atc['id'],'uid'=>$atc['user_id'],'state2'=>$state,'state3'=>$state,'id'=>$id]);if(($c['transport']??'vfn')==='hoppie'){$pdo->prepare("INSERT INTO cpdlc_messages(connection_id,sender_role,sender_user_id,message_type,message_text,response_options,transport) VALUES(:cid,'system',:uid,:type,:text,'','hoppie')")->execute(['cid'=>$id,'uid'=>$atc['user_id'],'type'=>$action==='accept'?'logon_accepted':'logon_rejected','text'=>$action==='accept'?'LOGON ACCEPTED':'LOGON REJECTED']);}}
  elseif($action==='close'){$pdo->prepare("UPDATE cpdlc_connections SET state='closed',closed_at=NOW(),last_activity_at=NOW() WHERE id=:id")->execute(['id'=>$id]);if(($c['transport']??'vfn')==='hoppie'){$pdo->prepare("INSERT INTO cpdlc_messages(connection_id,sender_role,sender_user_id,message_type,message_text,response_options,transport) VALUES(:cid,'system',:uid,'logoff','LOGOFF','','hoppie')")->execute(['cid'=>$id,'uid'=>$atc['user_id']]);}}
  elseif($action==='delete'){if(!in_array((string)$c['state'],['closed','rejected'],true))outCpdlc(['success'=>false,'message'=>'cpdlc_close_before_delete'],409);$pdo->prepare("DELETE FROM cpdlc_connections WHERE id=:id")->execute(['id'=>$id]);}
  elseif($action==='send'){$text=trim((string)($_POST['message']??''));$type=trim((string)($_POST['message_type']??'free_text'));$opts=strtoupper(trim((string)($_POST['response_options']??'')));if($c['state']!=='connected')outCpdlc(['success'=>false,'message'=>'cpdlc_not_connected'],409);if($text===''||mb_strlen($text)>500)outCpdlc(['success'=>false,'message'=>'cpdlc_invalid_message'],422);$transport=($c['transport']??'vfn')==='hoppie'?'hoppie':'vfn';$pdo->prepare("INSERT INTO cpdlc_messages(connection_id,sender_role,sender_user_id,message_type,message_text,response_options,transport)VALUES(:cid,'atc',:uid,:type,:text,:opts,:transport)")->execute(['cid'=>$id,'uid'=>$atc['user_id'],'type'=>$type,'text'=>$text,'opts'=>$opts,'transport'=>$transport]);$pdo->prepare("UPDATE cpdlc_connections SET last_activity_at=NOW() WHERE id=:id")->execute(['id'=>$id]);}
  vfnHoppieSyncStation($pdo,$hoppieStation,false);
 }
 $q=$pdo->prepare("SELECT c.*,u.real_name controller_name FROM cpdlc_connections c LEFT JOIN users u ON u.id=c.controller_user_id WHERE c.station_code=:station OR c.station_code=:hoppie OR c.station_code=:callsign OR c.controller_session_id=:sid ORDER BY FIELD(c.state,'requested','connected','rejected','closed'),c.last_activity_at DESC LIMIT 100");$q->execute(['station'=>$station,'hoppie'=>$hoppieStation,'callsign'=>$callsign,'sid'=>$atc['id']]);$connections=$q->fetchAll(PDO::FETCH_ASSOC);$messages=[];
 foreach($connections as $c){$m=$pdo->prepare("SELECT id,connection_id,sender_role,message_type,message_text,response_options,reply_to_id,status,DATE_FORMAT(created_at,'%H:%iZ') time FROM cpdlc_messages WHERE connection_id=:id ORDER BY id ASC LIMIT 200");$m->execute(['id'=>$c['id']]);$messages[(string)$c['id']]=$m->fetchAll(PDO::FETCH_ASSOC);}
 $gateway=null;if(vfnHoppieEnabled()){$g=$pdo->prepare("SELECT last_poll_at,next_poll_at,last_success_at,last_error FROM cpdlc_gateway_state WHERE station_code=:s");$g->execute(['s'=>$hoppieStation]);$gateway=$g->fetch(PDO::FETCH_ASSOC)?:null;}
 outCpdlc(['success'=>true,'connections'=>$connections,'messages'=>$messages,'station'=>$station,'hoppie_station'=>$hoppieStation,'callsign'=>$callsign,'hoppie_enabled'=>vfnHoppieEnabled(),'gateway'=>$gateway]);
}catch(Throwable $e){outCpdlc(['success'=>false,'message'=>'server_error'],500);}
