<?php
require_once __DIR__ . '/includes/session_bootstrap.php';
startVfnWebSession();
require_once __DIR__ . '/execute/config.php';
require_once __DIR__ . '/includes/language.php';
require_once __DIR__ . '/includes/web_session.php';
require_once __DIR__ . '/includes/ratings.php';
require_once __DIR__ . '/includes/atc_permissions.php';

$pdo = new PDO(
    "mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4",
    $dbUser,
    $dbPass,
    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
);

$user = null;
if (!empty($_SESSION['web_user_id']) && validateVfnWebSession($pdo)) {
    $stmt = $pdo->prepare(
        "SELECT id, username, real_name, rating_atc, rating_special, op_permission
         FROM users WHERE id = :id LIMIT 1"
    );
    $stmt->execute(['id' => (int)$_SESSION['web_user_id']]);
    $user = $stmt->fetch(PDO::FETCH_ASSOC) ?: null;
}

$rating = (int)($user['rating_atc'] ?? 0);
$specialRating = (int)($user['rating_special'] ?? 0);
$ratingInfo = getAtcRating($rating);
$specialRatingInfo = getSpecialRating($specialRating);
$positions = getAtcPositionPermissions($rating, $specialRating);
$canControl = $user !== null && canUseAtcClient($rating, $specialRating);
$atcAccessAllowed = !empty($atcLoginEnabled) || (int)($user['op_permission'] ?? 0) >= 5;
$canOpen = $user !== null && $atcAccessAllowed;
$voiceSessionToken = '';
if ($user && $canOpen) {
    try {
        $voiceSessionToken = (string)($_SESSION['web_voice_token'] ?? '');
        if ($voiceSessionToken !== '') {
            $voiceCheck = $pdo->prepare("SELECT token FROM user_sessions WHERE user_id=:uid AND token=:token AND is_active=1 LIMIT 1");
            $voiceCheck->execute(['uid'=>(int)$user['id'],'token'=>$voiceSessionToken]);
            $voiceSessionToken = (string)($voiceCheck->fetchColumn() ?: '');
        }
        if ($voiceSessionToken === '') {
            $voiceSessionToken = bin2hex(random_bytes(32));
            $voiceInsert = $pdo->prepare("INSERT INTO user_sessions (user_id,token,callsign,is_active,is_invisible,is_spectator) VALUES (:uid,:token,:callsign,1,1,1)");
            $voiceInsert->execute(['uid'=>(int)$user['id'],'token'=>$voiceSessionToken,'callsign'=>'ATCWEB'.(int)$user['id']]);
            $_SESSION['web_voice_token']=$voiceSessionToken;
        }
    } catch (Throwable $error) { $voiceSessionToken=''; }
}
?>
<!doctype html>
<html lang="<?php echo htmlspecialchars($currentLanguage); ?>">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo htmlspecialchars(t('atc_client_title')); ?> – VFN</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script>
(function(){
    const storageKey='vfn-atc-client-active';let instance=sessionStorage.getItem('vfn-atc-instance-id');
    if(!instance){instance=(window.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random());sessionStorage.setItem('vfn-atc-instance-id',instance);}
    window.__vfnAtcInstanceId=instance;let active=null;try{active=JSON.parse(localStorage.getItem(storageKey)||'null');}catch(error){}
    if(active&&active.instance!==instance&&Date.now()-Number(active.timestamp||0)<15000){window.__vfnAtcDuplicate=true;try{localStorage.setItem('vfn-atc-focus-request',String(Date.now()));if(typeof BroadcastChannel!=='undefined'){const channel=new BroadcastChannel('vfn-atc-client');channel.postMessage({type:'focus'});channel.close();}}catch(error){}setTimeout(()=>{if(window.opener){window.close();}else{window.location.replace('index.php');}},100);return;}
    window.__vfnAtcDuplicate=false;localStorage.setItem(storageKey,JSON.stringify({instance:instance,timestamp:Date.now()}));
})();
</script>
<style>
:root{--radar:#8dff9b;--bright:#c6ffcb;--dim:#3b7e48;--panel:#07150c;--line:#235f30;--danger:#ff6868}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:#010603;color:var(--radar);font-family:Consolas,"Courier New",monospace}
body:before{content:"";position:fixed;inset:0;pointer-events:none;background:repeating-linear-gradient(0deg,rgba(140,255,155,.025) 0,rgba(140,255,155,.025) 1px,transparent 1px,transparent 4px);z-index:20}
.screen{height:100%;display:grid;grid-template-rows:58px 1fr 34px;border:1px solid var(--line)}
.top,.status{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:0 18px;background:#041008;border-bottom:1px solid var(--line);letter-spacing:.08em}.top-actions{display:flex;gap:8px}.status{border:0;border-top:1px solid var(--line);font-size:12px;color:#70bd7a}
.brand{font-weight:bold;color:var(--bright)}.lamp{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:7px;background:var(--radar);box-shadow:0 0 10px var(--radar)}
.workspace{position:relative;display:grid;place-items:center;overflow:auto;padding:26px;background:radial-gradient(circle at center,rgba(31,95,43,.23),transparent 48%),linear-gradient(rgba(30,91,41,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(30,91,41,.12) 1px,transparent 1px),#010603;background-size:auto,50px 50px,50px 50px,auto}
.radar-ring{position:absolute;width:min(76vh,76vw);aspect-ratio:1;border:1px solid rgba(91,214,108,.15);border-radius:50%;pointer-events:none}.radar-ring:before,.radar-ring:after{content:"";position:absolute;left:50%;top:0;width:1px;height:100%;background:rgba(91,214,108,.12)}.radar-ring:after{transform:rotate(90deg)}
.panel{position:relative;z-index:2;width:min(900px,100%);padding:0;background:rgba(4,16,8,.94);border:1px solid var(--line);box-shadow:0 0 35px rgba(67,226,91,.09)}.window-content{padding:25px}.window-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:40px;padding:0 10px 0 14px;border-bottom:1px solid var(--line);background:#06120a;color:var(--bright);cursor:move;user-select:none;touch-action:none}.window-title{font-weight:bold;letter-spacing:.05em}.window-actions{display:flex;gap:6px}.window-action{min-width:30px;height:28px;border:1px solid var(--line);background:#07150c;color:var(--radar);font:inherit;cursor:pointer}.window-action:hover{border-color:var(--radar);background:#12351a}.window-action[data-action="dock"]{display:none}.panel.is-detached{width:100%;height:100%;max-width:none;border:0}.panel.is-detached .window-bar{cursor:default}.panel.is-detached .window-action[data-action="detach"]{display:none}.panel.is-detached .window-action[data-action="dock"]{display:inline-block}.mode-choice{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.mode-button{padding:18px;border:1px solid var(--line);background:#07150c;color:var(--radar);font:inherit;text-align:left;cursor:pointer}.mode-button strong{display:block;color:var(--bright);font-size:20px;margin-bottom:5px}.mode-button:hover,.mode-button.selected{background:#12351a;border-color:var(--radar)}.mode-button:disabled{opacity:.34;cursor:not-allowed}.selection-area[hidden]{display:none}
h1{margin:0 0 8px;color:var(--bright);font-size:24px}h2{font-size:15px;margin:24px 0 10px;color:var(--bright);text-transform:uppercase;letter-spacing:.09em}.muted{color:#6ea778}.identity{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.badge{padding:8px 11px;border:1px solid var(--line);background:#06120a}.positions{display:grid;grid-template-columns:repeat(7,minmax(92px,1fr));gap:9px}.position{min-height:104px;padding:12px;border:1px solid var(--line);background:#07150c;color:var(--radar);text-align:left}.position strong{display:block;font-size:18px;margin-bottom:7px}.position em{display:block;margin-top:7px;color:#ffd36a;font-size:10px;font-style:normal}.position.allowed{cursor:pointer}.position.allowed:hover,.position.selected{background:#12351a;border-color:var(--radar);box-shadow:inset 0 0 18px rgba(111,255,132,.12)}.position.locked{opacity:.34;cursor:not-allowed}.station-search{position:relative}.station-row{display:grid;grid-template-columns:1fr auto;gap:10px}.station-row input,.action{position:relative;z-index:3;min-height:44px;padding:0 13px;border:1px solid var(--line);background:#020a05;color:var(--bright);font:inherit;text-transform:uppercase;pointer-events:auto}.station-row input{width:100%;outline:none;caret-color:var(--bright);user-select:text}.station-row input:focus{border-color:var(--radar);box-shadow:0 0 0 2px rgba(141,255,155,.12)}.action{cursor:pointer;background:#12351a}.action:disabled{opacity:.35;cursor:not-allowed}.station-results{position:absolute;z-index:30;left:0;right:0;top:49px;max-height:245px;overflow:auto;border:1px solid var(--line);background:#020a05;box-shadow:0 18px 30px rgba(0,0,0,.65)}.station-result{display:block;width:100%;padding:10px 12px;border:0;border-bottom:1px solid #143d1e;background:transparent;color:var(--radar);font:inherit;text-align:left;cursor:pointer}.station-result:hover{background:#12351a}.station-result strong{color:var(--bright)}.station-result small{display:block;color:#70a97a;margin-top:3px;text-transform:none}.station-details{margin-top:10px;padding:10px 12px;border:1px solid var(--line);background:#06120a;color:#8edc98}.error{color:var(--danger);border-color:#773636}.fullscreen{border:1px solid var(--line);background:#07150c;color:var(--radar);padding:8px 11px;cursor:pointer}.denied{text-align:center;padding:45px 20px}.denied .symbol{font-size:55px;color:var(--danger)}
.position .supervision-note[hidden]{display:none}
.radar-desk{position:absolute;inset:0;z-index:3;overflow:hidden;background:#010603}.radar-desk[hidden]{display:none}.radar-map{position:absolute;inset:0;z-index:1;background:#07150c}.leaflet-container{background:#07150c;font-family:Consolas,"Courier New",monospace}.leaflet-tile-pane{filter:grayscale(1) sepia(.75) hue-rotate(75deg) saturate(1.8) brightness(.55)}.leaflet-control-attribution{opacity:.65}.radar-panel{position:absolute;z-index:1200;width:310px}.radar-panel.is-detached{z-index:auto}.radar-panel .window-content{padding:14px}.radar-status-panel{left:16px;top:16px}.radar-positions-panel{right:16px;top:16px}.radar-voice-panel{right:16px;bottom:16px}.radar-atis-panel{left:340px;top:16px;width:430px}.radar-data{display:grid;grid-template-columns:auto 1fr;gap:6px 12px;font-size:12px}.radar-data strong{color:var(--bright)}.active-position-list,.traffic-list{max-height:220px;overflow:auto}.active-position-row,.traffic-row{padding:7px 4px;border-bottom:1px solid #174223;font-size:12px}.traffic-row.radar-traffic-jump{display:block;width:100%;border-width:0 0 1px;background:transparent;color:var(--radar);font:inherit;text-align:left;cursor:pointer}.traffic-row.radar-traffic-jump:hover,.traffic-row.radar-traffic-jump:focus{background:#12351a;color:var(--bright);outline:none}.traffic-row .traffic-route{display:block;margin-top:3px;color:#78ad82;font-size:11px}.active-position-row .spec{color:#7ca686}.voice-row{display:flex;gap:7px}.voice-row input{min-width:0;flex:1;background:#020a05;border:1px solid var(--line);color:var(--bright);padding:7px;font:inherit}.voice-state{margin-top:8px;font-size:12px}.atis-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.atis-field{display:flex;flex-direction:column;gap:4px;font-size:11px;color:#70a97a}.atis-field.full{grid-column:1/-1}.atis-field input,.atis-field textarea{width:100%;border:1px solid var(--line);background:#020a05;color:var(--bright);padding:7px;font:inherit;resize:vertical}.atis-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}.atis-actions button{border:1px solid var(--line);background:#12351a;color:var(--bright);padding:7px 10px;font:inherit;cursor:pointer}.atis-status{margin-top:9px;padding-top:8px;border-top:1px solid #174223;font-size:11px;white-space:pre-wrap;color:#8edc98}.radar-target-diamond{width:11px;height:11px;background:#8dff9b;border:1px solid #d8ffdc;box-shadow:0 0 6px #61ff75;transform:rotate(45deg)}.radar-target-label{box-sizing:border-box;width:130px;height:48px;padding:2px 4px;color:#baffc2;background:rgba(1,12,5,.30);text-shadow:0 0 5px #000;font:bold 12px/14px Consolas;white-space:nowrap;cursor:move;user-select:none}.radar-target-label .radar-tag-row{display:flex;justify-content:space-between;gap:8px}.radar-target-label .radar-tag-route{color:#8dcb95;font-size:11px}.radar-target-label.is-dragging{color:#fff;outline:1px solid rgba(141,255,155,.55)}.radar-empty{color:#568c61;font-size:12px}
@media(max-width:800px){.positions{grid-template-columns:1fr 1fr}.screen{grid-template-rows:auto 1fr auto}.top,.status{padding:12px;flex-wrap:wrap}}
.detachable-window.is-collapsed .window-content{display:none}.detachable-window.is-collapsed{height:auto!important;min-height:40px}.atis-selector-row{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:10px}.atis-selector-row select{min-width:0;width:100%;border:1px solid var(--line);background:#020a05;color:var(--bright);padding:7px;font:inherit}.atis-managed{color:#ffd36a}.atis-field input:disabled,.atis-field textarea:disabled{opacity:.5}
.radar-chat-panel{left:16px;bottom:16px;width:430px}.atc-chat-tools{display:flex;align-items:center;gap:8px;margin-bottom:8px}.atc-chat-tools label{font-size:11px;color:#70a97a}.atc-chat-tools input{width:105px;border:1px solid var(--line);background:#020a05;color:var(--bright);padding:7px;font:inherit}.atc-chat-log{height:190px;overflow:auto;border:1px solid #174223;background:rgba(1,8,4,.75);padding:7px;font-size:12px}.atc-chat-line{display:grid;grid-template-columns:42px minmax(70px,auto) 1fr;gap:7px;padding:3px 0;overflow-wrap:anywhere}.atc-chat-time{color:#568c61}.atc-chat-sender{color:#8dff9b;font-weight:bold}.atc-chat-compose{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:8px}.atc-chat-compose input{min-width:0;border:1px solid var(--line);background:#020a05;color:var(--bright);padding:8px;font:inherit}.atc-chat-compose button{border:1px solid var(--line);background:#12351a;color:var(--bright);padding:7px 13px;font:inherit;cursor:pointer}.atc-chat-note{margin-top:7px;color:#ffd36a;font-size:11px}
.radar-context-menu{position:fixed;z-index:5000;min-width:225px;padding:6px;border:1px solid var(--radar);background:rgba(2,10,5,.98);box-shadow:0 10px 28px rgba(0,0,0,.72)}.radar-context-menu[hidden]{display:none}.radar-context-title{padding:7px 9px;border-bottom:1px solid var(--line);color:var(--bright);font-weight:bold}.radar-context-menu button{display:block;width:100%;padding:9px;border:0;background:transparent;color:var(--radar);font:inherit;text-align:left;cursor:pointer}.radar-context-menu button:hover{background:#12351a;color:var(--bright)}.radar-target-label.initial-contact{outline:2px solid #ffd36a;color:#fff6a4}.radar-target-diamond.initial-contact{background:#ffd36a;box-shadow:0 0 9px #ffd36a}.atc-fpl-dialog{position:fixed;z-index:5100;inset:0;display:grid;place-items:center;background:rgba(0,5,2,.66)}.atc-fpl-dialog[hidden]{display:none}.atc-fpl-box{width:min(620px,calc(100vw - 30px));border:1px solid var(--radar);background:#06120a;box-shadow:0 18px 50px #000}.atc-fpl-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:16px}.atc-fpl-grid label{display:grid;gap:4px;color:#70a97a;font-size:12px}.atc-fpl-grid label.full{grid-column:1/-1}.atc-fpl-grid input,.atc-fpl-grid textarea,.atc-fpl-grid select{width:100%;border:1px solid var(--line);background:#020a05;color:var(--bright);padding:8px;font:inherit}.atc-fpl-actions{display:flex;justify-content:flex-end;gap:8px;padding:0 16px 16px}.atc-fpl-status{margin-right:auto;align-self:center;font-size:11px;color:#ffd36a}
@keyframes radar-ident-flash{0%,100%{filter:none;opacity:1}50%{filter:brightness(3);opacity:.25}}.radar-target-diamond.ident-active,.radar-target-label.ident-active{animation:radar-ident-flash .42s linear infinite;color:#fff;background-color:#dfff76;box-shadow:0 0 18px #fff}</style>
</head>
<body>
<main class="screen">
    <header class="top"><div class="brand"><span class="lamp"></span>VFN ATC RADAR CLIENT</div><div><?php echo gmdate('H:i'); ?> UTC</div><div class="top-actions"><button class="fullscreen" id="fullscreenButton"><?php echo htmlspecialchars(t('atc_fullscreen')); ?></button><button class="fullscreen" id="logoutAtcPositionButton" hidden><?php echo htmlspecialchars(t('atc_position_logout')); ?></button><button class="fullscreen" id="closeAtcButton"><?php echo htmlspecialchars(t('atc_close')); ?></button></div></header>
    <section class="workspace"><div class="radar-ring"></div>
        <div class="panel detachable-window <?php echo $canOpen ? '' : 'error'; ?>" id="atcSetupWindow" data-window-key="atc-setup">
        <div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_setup_window')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach" title="<?php echo htmlspecialchars(t('atc_window_detach')); ?>">↗</button><button type="button" class="window-action" data-action="dock" title="<?php echo htmlspecialchars(t('atc_window_dock')); ?>">↙</button></span></div>
        <div class="window-content">
        <?php if (!$user): ?>
            <div class="denied"><div class="symbol">×</div><h1><?php echo htmlspecialchars(t('atc_login_required')); ?></h1><p><?php echo htmlspecialchars(t('atc_login_required_text')); ?></p></div>
        <?php elseif (!$atcAccessAllowed): ?>
            <div class="denied"><div class="symbol">×</div><h1><?php echo htmlspecialchars(t('atc_login_disabled')); ?></h1><p><?php echo htmlspecialchars(t('atc_login_disabled_text')); ?></p></div>
        <?php else: ?>
            <h1><?php echo htmlspecialchars(t('atc_mode_selection')); ?></h1>
            <p class="muted"><?php echo htmlspecialchars(t('atc_mode_selection_text')); ?></p>
            <div class="identity"><span class="badge"><?php echo htmlspecialchars($user['real_name'] ?: $user['username']); ?></span><span class="badge"><?php echo htmlspecialchars($ratingInfo['code'] . ' – ' . $ratingInfo['name']); ?></span><?php if ($specialRatingInfo): ?><span class="badge"><?php echo htmlspecialchars($specialRatingInfo['code'] . ' – ' . $specialRatingInfo['name']); ?></span><?php endif; ?></div>
            <div class="mode-choice">
                <button class="mode-button" id="controllerMode" <?php echo $canControl ? '' : 'disabled'; ?>><strong><?php echo htmlspecialchars(t('atc_mode_controller')); ?></strong><span><?php echo htmlspecialchars($canControl ? t('atc_mode_controller_text') : t('atc_mode_controller_denied')); ?></span></button>
                <button class="mode-button" id="spectatorMode"><strong><?php echo htmlspecialchars(t('atc_mode_spectator')); ?></strong><span><?php echo htmlspecialchars(t('atc_mode_spectator_text')); ?></span></button>
            </div>
            <div class="selection-area" id="selectionArea" hidden>
            <h1><?php echo htmlspecialchars(t('atc_position_selection')); ?></h1>
            <h2><?php echo htmlspecialchars(t('atc_station_identifier')); ?></h2>
            <div class="station-search"><div class="station-row"><input id="station" type="search" maxlength="80" placeholder="EDDM / München / EDMM" autocomplete="off" spellcheck="false" autofocus><button class="action" id="continueButton" disabled><?php echo htmlspecialchars(t('atc_continue')); ?></button></div><div class="station-results" id="stationResults" hidden></div></div>
            <div class="station-details" id="stationDetails" hidden></div>
            <h2><?php echo htmlspecialchars(t('atc_allowed_positions')); ?></h2>
            <div class="positions">
            <?php foreach ($positions as $position): ?>
                <button class="position <?php echo $position['allowed'] ? 'allowed' : 'locked'; ?>" data-code="<?php echo htmlspecialchars($position['code']); ?>" data-rank-allowed="<?php echo $position['allowed'] ? '1' : '0'; ?>" <?php echo $position['allowed'] ? '' : 'disabled'; ?>>
                    <strong><?php echo htmlspecialchars($position['code']); ?></strong>
                    <span><?php echo htmlspecialchars(t($position['name_key'])); ?></span>
                    <?php if ($position['supervision_required']): ?><em class="supervision-note"><?php echo htmlspecialchars(t('atc_supervision_required')); ?></em><?php endif; ?>
                </button>
            <?php endforeach; ?>
            </div>
            <p class="muted" id="selectionHint"><?php echo htmlspecialchars(t('atc_choose_station_position')); ?></p>
            </div>
        <?php endif; ?>
        </div></div>
        <div class="radar-desk" id="radarDesk" hidden>
            <div class="radar-map" id="atcRadarMap"></div>
            <div class="panel radar-panel radar-status-panel detachable-window" data-window-key="radar-status"><div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_radar_session')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach">↗</button><button type="button" class="window-action" data-action="dock">↙</button></span></div><div class="window-content"><div class="radar-data"><span><?php echo htmlspecialchars(t('atc_callsign')); ?></span><strong id="radarCallsign">–</strong><span><?php echo htmlspecialchars(t('atc_station_identifier')); ?></span><strong id="radarStation">–</strong><span><?php echo htmlspecialchars(t('atc_allowed_positions')); ?></span><strong id="radarScope">–</strong><span><?php echo htmlspecialchars(t('atc_map_profile')); ?></span><strong id="radarMapProfile">–</strong></div><h2><?php echo htmlspecialchars(t('atc_live_traffic')); ?></h2><div class="traffic-list" id="radarTrafficList"></div></div></div>
            <div class="panel radar-panel radar-positions-panel detachable-window" data-window-key="active-positions"><div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_active_positions')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach">↗</button><button type="button" class="window-action" data-action="dock">↙</button></span></div><div class="window-content active-position-list" id="activePositionList"></div></div>
            <div class="panel radar-panel radar-voice-panel detachable-window" data-window-key="atc-voice"><div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_voice')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach">↗</button><button type="button" class="window-action" data-action="dock">↙</button></span></div><div class="window-content"><div class="voice-row"><input id="atcVoiceFrequency" list="atcVoiceFrequencyList" inputmode="decimal" placeholder="122.800"><datalist id="atcVoiceFrequencyList"></datalist><button class="window-action" id="atcVoiceConnect" type="button">RX</button><button class="window-action" id="atcVoicePtt" type="button">PTT</button></div><div class="voice-row" style="margin-top:7px"><input id="atcVoiceReference" maxlength="12" placeholder="ICAO reference (e.g. EDDM)"></div><div class="voice-state" id="atcVoiceState"><?php echo htmlspecialchars(t('atc_voice_disconnected')); ?></div></div></div>
            <div class="panel radar-panel radar-atis-panel detachable-window" id="atcAtisPanel" data-window-key="atc-atis"><div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_atis_control')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach">↗</button><button type="button" class="window-action" data-action="dock">↙</button></span></div><div class="window-content"><form id="atcAtisForm"><div class="atis-grid"><label class="atis-field"><span><?php echo htmlspecialchars(t('atc_atis_arrival_runways')); ?></span><input name="arrival_runways" maxlength="64" placeholder="26R"></label><label class="atis-field"><span><?php echo htmlspecialchars(t('atc_atis_departure_runways')); ?></span><input name="departure_runways" maxlength="64" placeholder="26L"></label><label class="atis-field"><span><?php echo htmlspecialchars(t('atc_atis_transition_level')); ?></span><input name="transition_level" maxlength="16" placeholder="FL70"></label><label class="atis-field"><span><?php echo htmlspecialchars(t('atc_atis_transition_altitude')); ?></span><input name="transition_altitude" maxlength="16" placeholder="5000"></label><label class="atis-field full"><span><?php echo htmlspecialchars(t('atc_atis_approach_type')); ?></span><input name="approach_type" maxlength="64" placeholder="ILS approach"></label><label class="atis-field full"><span><?php echo htmlspecialchars(t('atc_atis_remarks')); ?></span><textarea name="remarks" maxlength="500" rows="3"></textarea></label></div><div class="atis-actions"><button type="submit"><?php echo htmlspecialchars(t('atc_atis_save')); ?></button><button type="button" id="atcAtisAutomatic"><?php echo htmlspecialchars(t('atc_atis_automatic')); ?></button></div><div class="atis-status" id="atcAtisStatus">–</div></form></div></div>
            <div class="panel radar-panel radar-chat-panel detachable-window" data-window-key="atc-chat"><div class="window-bar"><span class="window-title"><?php echo htmlspecialchars(t('atc_chat')); ?></span><span class="window-actions"><button type="button" class="window-action" data-action="detach">↗</button><button type="button" class="window-action" data-action="dock">↙</button></span></div><div class="window-content"><div class="atc-chat-tools"><label for="atcChatFrequency"><?php echo htmlspecialchars(t('atc_chat_frequency')); ?></label><input id="atcChatFrequency" inputmode="decimal" maxlength="7" placeholder="122.800"></div><div class="atc-chat-log" id="atcChatLog"></div><form class="atc-chat-compose" id="atcChatForm"><input id="atcChatMessage" maxlength="255" autocomplete="off" placeholder="<?php echo htmlspecialchars(t('atc_chat_placeholder')); ?>"><button type="submit" id="atcChatSend"><?php echo htmlspecialchars(t('atc_chat_send')); ?></button></form><div class="atc-chat-note" id="atcChatNote" hidden><?php echo htmlspecialchars(t('atc_chat_receive_only')); ?></div></div></div>
            <div class="radar-context-menu" id="radarContextMenu" hidden><div class="radar-context-title" id="radarContextTitle">–</div><button type="button" data-command="initial-contact"><?php echo htmlspecialchars(t('atc_context_initial_contact')); ?></button><button type="button" data-command="edit-flightplan"><?php echo htmlspecialchars(t('atc_context_edit_flightplan')); ?></button><button type="button" data-command="center-target"><?php echo htmlspecialchars(t('atc_context_center_target')); ?></button></div>
            <div class="atc-fpl-dialog" id="atcFlightplanDialog" hidden><form class="atc-fpl-box" id="atcFlightplanForm"><div class="window-bar"><span class="window-title" id="atcFlightplanTitle"><?php echo htmlspecialchars(t('atc_flightplan_title')); ?></span><button type="button" class="window-action" id="atcFlightplanClose">×</button></div><div class="atc-fpl-grid"><label><?php echo htmlspecialchars(t('atc_flightplan_rules')); ?><select name="flight_rules"><option>IFR</option><option>VFR</option><option>Y</option><option>Z</option></select></label><label><?php echo htmlspecialchars(t('atc_flightplan_type')); ?><select name="flight_type"><option value="S">S – Scheduled</option><option value="N">N – Non-scheduled</option><option value="G">G – General aviation</option><option value="M">M – Military</option><option value="X">X – Other</option></select></label><label><?php echo htmlspecialchars(t('atc_flightplan_departure')); ?><input name="departure_airport" class="icao-uppercase" maxlength="8"></label><label><?php echo htmlspecialchars(t('atc_flightplan_arrival')); ?><input name="arrival_airport" class="icao-uppercase" maxlength="8"></label><label><?php echo htmlspecialchars(t('atc_flightplan_alternate1')); ?><input name="alternate1_airport" class="icao-uppercase" maxlength="8"></label><label><?php echo htmlspecialchars(t('atc_flightplan_alternate2')); ?><input name="alternate2_airport" class="icao-uppercase" maxlength="8"></label><label><?php echo htmlspecialchars(t('atc_flightplan_level')); ?><input name="cruising_level" maxlength="20"></label><label><?php echo htmlspecialchars(t('atc_flightplan_speed')); ?><input name="cruising_speed" maxlength="20"></label><label class="full"><?php echo htmlspecialchars(t('atc_flightplan_route')); ?><textarea name="route_text" rows="4" maxlength="5000"></textarea></label><label class="full"><?php echo htmlspecialchars(t('atc_flightplan_remarks')); ?><textarea name="remarks" rows="3" maxlength="2000"></textarea></label></div><div class="atc-fpl-actions"><span class="atc-fpl-status" id="atcFlightplanStatus"></span><button type="button" class="window-action" id="atcFlightplanCancel"><?php echo htmlspecialchars(t('atc_flightplan_cancel')); ?></button><button type="submit" class="action"><?php echo htmlspecialchars(t('atc_flightplan_save')); ?></button></div></form></div>
        </div>
    </section>
    <footer class="status"><span>SYS: ONLINE</span><span>AUTH: <?php echo $canOpen ? 'VALID' : 'DENIED'; ?></span><span>VFN ATC CORE / PHASE 1</span></footer>
</main>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
if(!window.__vfnAtcDuplicate){
document.getElementById('fullscreenButton').addEventListener('click',function(){document.documentElement.requestFullscreen?.().catch(()=>{});});
document.getElementById('closeAtcButton').addEventListener('click',async function(){this.disabled=true;try{await fetch('execute/atc_session_stop.php',{method:'POST',keepalive:true});}catch(error){}try{window.close();}catch(error){}setTimeout(()=>{if(!window.closed)window.location.replace('index.php');},120);});
const atcInstanceId=window.__vfnAtcInstanceId;const detachedAtcWindows=new Set();let atcChannel=null;
function writeAtcHeartbeat(){localStorage.setItem('vfn-atc-client-active',JSON.stringify({instance:atcInstanceId,timestamp:Date.now()}));}
function focusActiveAtcWindow(){for(const popup of detachedAtcWindows){if(popup&&!popup.closed){popup.focus();return;}}window.focus();}
writeAtcHeartbeat();const atcHeartbeatTimer=setInterval(writeAtcHeartbeat,1000);
if(typeof BroadcastChannel!=='undefined'){atcChannel=new BroadcastChannel('vfn-atc-client');atcChannel.addEventListener('message',event=>{if(event.data?.type==='focus')focusActiveAtcWindow();});}
window.addEventListener('storage',event=>{if(event.key==='vfn-atc-focus-request')focusActiveAtcWindow();});
window.addEventListener('beforeunload',()=>{clearInterval(atcHeartbeatTimer);atcChannel?.close();for(const popup of detachedAtcWindows){try{popup.close();}catch(error){}}try{const active=JSON.parse(localStorage.getItem('vfn-atc-client-active')||'null');if(active?.instance===atcInstanceId)localStorage.removeItem('vfn-atc-client-active');}catch(error){}});
function initializeAtcWindow(panel){
    const workspace=panel.closest('.workspace');const dockParent=panel.parentElement;const bar=panel.querySelector('.window-bar');const detachButton=panel.querySelector('[data-action="detach"]');const dockButton=panel.querySelector('[data-action="dock"]');const key=panel.dataset.windowKey||panel.id;let popup=null,drag=null,closeWatch=null;
    const actions=bar.querySelector('.window-actions');const collapseButton=document.createElement('button');collapseButton.type='button';collapseButton.className='window-action';collapseButton.dataset.action='collapse';actions.insertBefore(collapseButton,actions.firstChild);function setCollapsed(collapsed){panel.classList.toggle('is-collapsed',collapsed);collapseButton.textContent=collapsed?'□':'–';collapseButton.title=collapsed?'Fenster ausklappen':'Fenster einklappen';localStorage.setItem('vfn-atc-window-collapsed-'+key,collapsed?'1':'0');if(popup&&!popup.closed)popup.resizeTo(Math.max(360,popup.outerWidth),collapsed?125:Math.max(420,popup.outerHeight));}setCollapsed(localStorage.getItem('vfn-atc-window-collapsed-'+key)==='1');collapseButton.addEventListener('click',event=>{event.stopPropagation();setCollapsed(!panel.classList.contains('is-collapsed'));});
    function savePosition(){if(panel.classList.contains('is-detached'))return;localStorage.setItem('vfn-atc-window-'+key,JSON.stringify({left:panel.style.left,top:panel.style.top}));}
    function restorePosition(){try{const saved=JSON.parse(localStorage.getItem('vfn-atc-window-'+key)||'null');if(saved?.left&&saved?.top){panel.style.position='absolute';panel.style.left=saved.left;panel.style.top=saved.top;return true;}}catch(error){}return false;}
    function dock(){if(!popup)return;detachedAtcWindows.delete(popup);dockParent.appendChild(panel);panel.classList.remove('is-detached');if(!restorePosition()){panel.style.position='';panel.style.left='';panel.style.top='';}try{popup.close();}catch(error){}popup=null;if(closeWatch){clearInterval(closeWatch);closeWatch=null;}}
    function detach(){if(popup&&!popup.closed){popup.focus();return;}popup=window.open('','vfn_atc_'+key.replace(/[^a-z0-9]/gi,'_'),'popup=yes,width=1100,height=760,resizable=yes,scrollbars=yes');if(!popup)return;detachedAtcWindows.add(popup);popup.document.open();popup.document.write('<!doctype html><html lang="<?php echo addslashes($currentLanguage); ?>"><head><meta charset="utf-8"><title>'+panel.querySelector('.window-title').textContent.replace(/[<>&]/g,'')+' – VFN</title>'+Array.from(document.querySelectorAll('style')).map(style=>'<style>'+style.textContent+'@keyframes radar-ident-flash{0%,100%{filter:none;opacity:1}50%{filter:brightness(3);opacity:.25}}.radar-target-diamond.ident-active,.radar-target-label.ident-active{animation:radar-ident-flash .42s linear infinite;color:#fff;background-color:#dfff76;box-shadow:0 0 18px #fff}</style>').join('')+'</head><body></body></html>');popup.document.close();popup.document.body.appendChild(panel);panel.classList.add('is-detached');panel.style.position='relative';panel.style.left='';panel.style.top='';popup.document.documentElement.style.overflow='auto';popup.document.body.style.overflow='auto';closeWatch=setInterval(()=>{if(popup&&popup.closed)dock();},400);}
    detachButton.addEventListener('click',event=>{event.stopPropagation();detach();});dockButton.addEventListener('click',event=>{event.stopPropagation();dock();});
    bar.addEventListener('pointerdown',event=>{if(panel.classList.contains('is-detached')||event.target.closest('button'))return;const panelRect=panel.getBoundingClientRect();const workspaceRect=workspace.getBoundingClientRect();panel.style.position='absolute';panel.style.left=(panelRect.left-workspaceRect.left+workspace.scrollLeft)+'px';panel.style.top=(panelRect.top-workspaceRect.top+workspace.scrollTop)+'px';drag={x:event.clientX,y:event.clientY,left:parseFloat(panel.style.left),top:parseFloat(panel.style.top),pointer:event.pointerId};bar.setPointerCapture(event.pointerId);});
    bar.addEventListener('pointermove',event=>{if(!drag||event.pointerId!==drag.pointer)return;const maxLeft=Math.max(0,workspace.scrollWidth-panel.offsetWidth);const maxTop=Math.max(0,workspace.scrollHeight-panel.offsetHeight);panel.style.left=Math.max(0,Math.min(maxLeft,drag.left+event.clientX-drag.x))+'px';panel.style.top=Math.max(0,Math.min(maxTop,drag.top+event.clientY-drag.y))+'px';});
    function finishDrag(event){if(!drag||event.pointerId!==drag.pointer)return;drag=null;savePosition();}
    bar.addEventListener('pointerup',finishDrag);bar.addEventListener('pointercancel',finishDrag);restorePosition();
    panel.__dockAtcWindow=dock;
}
document.querySelectorAll('.detachable-window').forEach(initializeAtcWindow);
<?php if ($canOpen): ?>
let selectedMode='',selectedPosition='',selectedStation=null,searchTimer=null,searchController=null,searchSequence=0;const atcPanel=document.getElementById('atcSetupWindow');const station=document.getElementById('station');const next=document.getElementById('continueButton');const results=document.getElementById('stationResults');const details=document.getElementById('stationDetails');const selectionArea=document.getElementById('selectionArea');const selectionHint=document.getElementById('selectionHint');
const ATC_VOICE_TOKEN=<?php echo json_encode($voiceSessionToken); ?>;const ATC_VOICE_URL=<?php echo json_encode((string)($voiceServiceWebSocketUrl ?? ''), JSON_UNESCAPED_SLASHES); ?>||((location.protocol==='https:'?'wss://':'ws://')+location.hostname+':8090');let currentAtcSession=null,radarMap=null,radarTrafficLayer=null,radarFirLayer=null,atcHeartbeatPoll=null,atcTrafficPoll=null,atcChatPoll=null,atcChatSinceId=0,atcChatFrequencyValue='',atcChatRequestInFlight=false,atcVoiceSocket=null,atcVoiceConnected=false,voicePlaybackContext=null,voicePlaybackTime=0,atcMicStream=null,atcMicContext=null,atcMicProcessor=null,atcMicSource=null,atcMicGain=null,atcVoiceSequence=0,radarContextTarget=null,initialContactCallsign='';const radarTargets=new Map(),radarLabelOffsets=new Map(),atcChatRenderedIds=new Set();const atcChatFrequency=document.getElementById('atcChatFrequency'),atcChatLog=document.getElementById('atcChatLog'),atcChatForm=document.getElementById('atcChatForm'),atcChatMessage=document.getElementById('atcChatMessage'),atcChatSend=document.getElementById('atcChatSend'),atcChatNote=document.getElementById('atcChatNote');
function initializeRadarMap(){if(radarMap)return;radarMap=L.map('atcRadarMap',{zoomControl:true,worldCopyJump:false,maxBoundsViscosity:1}).setView([51,10],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap · VFN'}).addTo(radarMap);radarTrafficLayer=L.layerGroup().addTo(radarMap);radarMap.on('zoomend',()=>{refreshRadarTargetGeometry();refreshRadarTrails();});}
function airportRadarLimits(session,center){const profile=String(session.map_profile||'');const settings={airport_info:{radius:12,min:11,max:19,zoom:14},airport_delivery:{radius:10,min:12,max:19,zoom:15},airport_ground:{radius:8,min:13,max:19,zoom:16},airport_tower:{radius:45,min:9,max:19,zoom:11},terminal_approach:{radius:150,min:7,max:19,zoom:9},terminal_departure:{radius:150,min:7,max:19,zoom:9}}[profile];if(!settings||!center)return null;const latitude=Number(center.latitude),longitude=Number(center.longitude),latDelta=settings.radius/60,lonDelta=settings.radius/(60*Math.max(.2,Math.cos(latitude*Math.PI/180)));return{bounds:L.latLngBounds([latitude-latDelta,longitude-lonDelta],[latitude+latDelta,longitude+lonDelta]),min:settings.min,max:settings.max,zoom:settings.zoom};}
function applyAirportRadarLimits(session,center){const limits=airportRadarLimits(session,center);if(!limits)return;radarMap.setMinZoom(limits.min);radarMap.setMaxZoom(limits.max);radarMap.setMaxBounds(limits.bounds);if(!radarMap.__vfnCentered){radarMap.setView([Number(center.latitude),Number(center.longitude)],limits.zoom);radarMap.__vfnCentered=true;}}
function renderActivePositions(items){const list=document.getElementById('activePositionList');list.innerHTML='';if(!items.length){list.innerHTML='<div class="radar-empty">–</div>';return;}items.forEach(item=>{const row=document.createElement('div');row.className='active-position-row';row.innerHTML='<strong>'+escapeText(item.callsign)+'</strong><br><span'+(Number(item.is_spectator)?' class="spec"':'')+'>'+escapeText(item.position_code)+(Number(item.is_spectator)?' · SPEC':'')+'</span><br><span class="spec">'+escapeText(item.controller_name||'–')+'</span>';list.appendChild(row);});}
function normalizeAtcFrequency(value){const match=String(value||'').trim().replace(',','.').match(/^(\d{3})(?:\.(\d{0,3}))?$/);return match?match[1]+'.'+String(match[2]||'').padEnd(3,'0').slice(0,3):'';}
let atisAirports=[],selectedAtisAirport='',atisReloadTimer=null;
const atisChannel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('vfn-atc-atis'):null;
function atisPanelAvailable(session){return Boolean(session)&&!Number(session.is_spectator||session.spectator);}
function ensureAtisSelector(){
    const form=document.getElementById('atcAtisForm');let select=document.getElementById('atcAtisAirport');
    if(select)return select;
    const row=document.createElement('div');row.className='atis-selector-row';
    select=document.createElement('select');select.id='atcAtisAirport';select.setAttribute('aria-label','ATIS airport');
    const popupButton=document.createElement('button');popupButton.type='button';popupButton.className='window-action';popupButton.id='atcAtisNewWindow';popupButton.textContent='＋';popupButton.title='ATIS in neuem Fenster öffnen';
    row.append(select,popupButton);form.parentElement.insertBefore(row,form);
    let hidden=form.elements.airport;if(!hidden){hidden=document.createElement('input');hidden.type='hidden';hidden.name='airport';form.prepend(hidden);}
    select.addEventListener('change',()=>selectAtisAirport(select.value));
    popupButton.addEventListener('click',()=>{if(!selectedAtisAirport)return;const id='vfn_atis_'+selectedAtisAirport+'_'+Date.now();window.open('atc_atis_window.php?airport='+encodeURIComponent(selectedAtisAirport),id,'popup=yes,width=560,height=720,resizable=yes,scrollbars=yes');});
    return select;
}
function storeAtisDraft(){
    if(!selectedAtisAirport)return;const form=document.getElementById('atcAtisForm'),draft={};
    ['arrival_runways','departure_runways','transition_level','transition_altitude','approach_type','remarks'].forEach(name=>draft[name]=form.elements[name]?.value||'');
    sessionStorage.setItem('vfn-atc-atis-draft-'+selectedAtisAirport,JSON.stringify(draft));
}
async function selectAtisAirport(airport){
    if(selectedAtisAirport&&selectedAtisAirport!==airport)storeAtisDraft();
    selectedAtisAirport=String(airport||'').toUpperCase();localStorage.setItem('vfn-atc-last-atis',selectedAtisAirport);
    const form=document.getElementById('atcAtisForm');if(form.elements.airport)form.elements.airport.value=selectedAtisAirport;
    await loadAtisSettings(false);
}
function renderAtisSettings(data){
    const form=document.getElementById('atcAtisForm'),settings=data.settings||{},broadcast=data.broadcast||null;
    let draft=null;try{draft=JSON.parse(sessionStorage.getItem('vfn-atc-atis-draft-'+selectedAtisAirport)||'null');}catch(error){}
    ['arrival_runways','departure_runways','transition_level','transition_altitude','approach_type','remarks'].forEach(name=>{if(form.elements[name])form.elements[name].value=draft?.[name]??settings[name]??'';});
    const airport=atisAirports.find(item=>item.icao===selectedAtisAirport)||{};const editable=Number(airport.editable)!==0;
    form.querySelectorAll('input:not([type="hidden"]),textarea,button').forEach(item=>item.disabled=!editable);
    const mode=Number(settings.is_active)?<?php echo json_encode(t('atc_atis_manual')); ?>:<?php echo json_encode(t('atc_atis_auto')); ?>;
    const details=broadcast?['<?php echo addslashes(t('atc_atis_current')); ?>: '+(broadcast.info_letter||'–'),broadcast.frequency?broadcast.frequency+' MHz':'',broadcast.active_runway?'RWY '+broadcast.active_runway:''].filter(Boolean).join(' · '):'';
    const manager=airport.managed_by?'\nDurch '+airport.managed_position+' · '+airport.managed_by+' verwaltet':'';
    document.getElementById('atcAtisStatus').textContent=(data.airport||'')+' · '+mode+(details?'\n'+details:'')+manager;
}
async function loadAtisAirports(){
    const panel=document.getElementById('atcAtisPanel'),available=atisPanelAvailable(currentAtcSession);panel.hidden=!available;
    if(!available){document.getElementById('atcAtisStatus').textContent=<?php echo json_encode(t('atc_atis_not_available')); ?>;return;}
    const select=ensureAtisSelector();const response=await fetch('execute/atc_atis_airports.php',{cache:'no-store'}),data=await response.json();
    if(!response.ok||!data.success)throw new Error(data.message||'atis_airports_failed');atisAirports=Array.isArray(data.airports)?data.airports:[];select.innerHTML='';
    atisAirports.forEach(item=>{const option=document.createElement('option');option.value=item.icao;option.textContent=item.icao+' · '+item.frequency+' · '+(item.info_letter||'ATIS')+(item.managed_by?' · '+item.managed_position:'');select.appendChild(option);});
    const preferred=[selectedAtisAirport,localStorage.getItem('vfn-atc-last-atis'),currentAtcSession?.station_code,atisAirports[0]?.icao].find(code=>atisAirports.some(item=>item.icao===code));
    if(!preferred){selectedAtisAirport='';document.getElementById('atcAtisStatus').textContent=<?php echo json_encode(t('atc_atis_not_available')); ?>;return;}
    select.value=preferred;selectedAtisAirport=preferred;const form=document.getElementById('atcAtisForm');if(form.elements.airport)form.elements.airport.value=preferred;await loadAtisSettings(false);
}
async function loadAtisSettings(refreshAirports=true){
    if(refreshAirports)return loadAtisAirports();if(!selectedAtisAirport)return;
    try{const response=await fetch('execute/atc_atis_settings.php?airport='+encodeURIComponent(selectedAtisAirport),{cache:'no-store'}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'atis_load_failed');renderAtisSettings(data);}catch(error){document.getElementById('atcAtisStatus').textContent=error.message;}
}
async function saveAtisSettings(action='save'){
    const form=document.getElementById('atcAtisForm'),status=document.getElementById('atcAtisStatus'),body=new FormData(form);body.set('action',action);body.set('airport',selectedAtisAirport);form.querySelectorAll('button').forEach(button=>button.disabled=true);
    try{const response=await fetch('execute/atc_atis_settings.php',{method:'POST',body}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'atis_save_failed');sessionStorage.removeItem('vfn-atc-atis-draft-'+selectedAtisAirport);renderAtisSettings(data);status.textContent=(action==='automatic'?<?php echo json_encode(t('atc_atis_auto_saved')); ?>:<?php echo json_encode(t('atc_atis_saved')); ?>)+'\n'+status.textContent;atisChannel?.postMessage({type:'updated',airport:selectedAtisAirport});clearTimeout(atisReloadTimer);atisReloadTimer=setTimeout(()=>loadAtisSettings(true),35000);}catch(error){status.textContent=error.message;}finally{form.querySelectorAll('button').forEach(button=>button.disabled=false);}
}
atisChannel?.addEventListener('message',event=>{if(event.data?.type==='updated'&&event.data.airport===selectedAtisAirport)loadAtisSettings(true);});
function setSessionDisplay(session){const previousCallsign=currentAtcSession?.callsign||'';currentAtcSession=session;document.getElementById('radarCallsign').textContent=session.callsign||'–';document.getElementById('radarStation').textContent=(session.station_code||'–')+' / '+(session.position_code||'–');document.getElementById('radarScope').textContent=Array.isArray(session.scope_positions)?session.scope_positions.join(', '):String(session.scope_positions||'').split(',').join(', ');document.getElementById('radarMapProfile').textContent=session.map_profile||'–';const frequencyInput=document.getElementById('atcVoiceFrequency');const selectedFrequency=previousCallsign===session.callsign?normalizeAtcFrequency(frequencyInput.value):'';const frequencyList=document.getElementById('atcVoiceFrequencyList');frequencyList.innerHTML='';(session.available_frequencies||[]).forEach(item=>{const option=document.createElement('option');option.value=normalizeAtcFrequency(item.frequency||'');option.label=(item.callsign||'')+(item.source?' · '+item.source:'');frequencyList.appendChild(option);});frequencyInput.value=selectedFrequency||normalizeAtcFrequency(session.frequency||((session.available_frequencies||[])[0]?.frequency)||'');document.getElementById('atcVoiceReference').value=session.station_code||'';document.getElementById('atcVoicePtt').hidden=Number(session.is_spectator||session.spectator)?true:false;}
async function loadRadarMaterial(session){
    initializeRadarMap();
    radarMap.__vfnCentered=false;
    radarMap.setMinZoom(2);
    radarMap.setMaxZoom(19);
    radarMap.setMaxBounds([[-85,-180],[85,180]]);
    if(radarFirLayer){radarFirLayer.remove();radarFirLayer=null;}
    const position=String(session.position_code||'').toUpperCase();
    try{
        let response=null;
        let filter=null;
        if(position==='CTR'){
            const station=String(session.station_code||'').toUpperCase();
            const detailedResponse=await fetch(
                'execute/sector_boundaries.php?station='+encodeURIComponent(station)
            );
            if(detailedResponse.ok){
                const detailed=await detailedResponse.json();
                radarFirLayer=L.geoJSON(detailed.geojson||{type:'FeatureCollection',features:[]},{
                    style:{color:'#78ff91',weight:2,fillColor:'#123b1d',fillOpacity:.16}
                }).addTo(radarMap);
            }else{
                response=await fetch('execute/fir_boundaries.php');
                const fallback=String(session.radar_boundary_code||'').toUpperCase();
                if(!response.ok)throw new Error('Boundary data unavailable');
                const geo=await response.json();
                const geoHasExactSector=(geo.features||[]).some(feature=>
                    String(feature.properties?.id||'').toUpperCase()===station
                );
                filter=feature=>{
                    const id=String(feature.properties?.id||'').toUpperCase();
                    return id===station||(!geoHasExactSector&&id===fallback);
                };
                radarFirLayer=L.geoJSON(geo,{
                    filter:filter,
                    style:{
                        color:geoHasExactSector?'#78ff91':'#a89070',weight:2,
                        fillColor:geoHasExactSector?'#123b1d':'#302a20',
                        fillOpacity:geoHasExactSector ? .16 : .05,
                        dashArray:geoHasExactSector?null:'3 8'
                    }
                }).addTo(radarMap);
                response=null;
            }
        }else if(position==='APP'||position==='DEP'){
            response=await fetch('execute/tracon_boundaries.php');
            const station=String(session.station_code||'').toUpperCase();
            filter=feature=>{
                const properties=feature.properties||{};
                const prefixes=Array.isArray(properties.prefix)?properties.prefix:[properties.prefix];
                const suffix=String(properties.suffix||'APP').toUpperCase();
                return prefixes.some(prefix=>String(prefix||'').toUpperCase()===station)&&suffix===position;
            };
        }
        if(response){
            if(!response.ok)throw new Error('Boundary data unavailable');
            const geo=await response.json();
            radarFirLayer=L.geoJSON(geo,{filter:filter,style:{
                color:'#78ff91',weight:2,fillColor:'#123b1d',fillOpacity:.16
            }}).addTo(radarMap);
        }
        if(radarFirLayer&&radarFirLayer.getLayers().length){
            const bounds=radarFirLayer.getBounds().pad(.18);
            radarMap.fitBounds(bounds,{padding:[30,30]});
            const fittedZoom=radarMap.getZoom();
            radarMap.setMinZoom(Math.max(2,fittedZoom-1));
            radarMap.setMaxZoom(19);
            radarMap.setMaxBounds(bounds);
            radarMap.__vfnCentered=true;
        }
    }catch(error){console.error(error);}
    setTimeout(()=>radarMap.invalidateSize(),80);
}
async function pollAtcHeartbeat(){try{const response=await fetch('execute/atc_heartbeat.php',{cache:'no-store'});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'heartbeat_failed');setSessionDisplay(data.session);renderActivePositions(Array.isArray(data.active_positions)?data.active_positions:[]);}catch(error){clearInterval(atcHeartbeatPoll);clearInterval(atcTrafficPoll);clearInterval(atcChatPoll);document.getElementById('radarCallsign').textContent=error.message;if(error.message==='atc_session_inactive'||error.message==='atc_login_disabled')setTimeout(()=>window.location.reload(),250);}}
function radarOffsetStorageKey(){return'vfn-atc-label-offsets-'+String(currentAtcSession?.callsign||'default').replace(/[^A-Z0-9_-]/gi,'_');}
function loadRadarLabelOffsets(){if(radarLabelOffsets.size)return;try{const saved=JSON.parse(localStorage.getItem(radarOffsetStorageKey())||'{}');Object.entries(saved).forEach(([callsign,offset])=>{if(Number.isFinite(Number(offset?.x))&&Number.isFinite(Number(offset?.y)))radarLabelOffsets.set(callsign,{x:Number(offset.x),y:Number(offset.y),ratio:Number.isFinite(Number(offset?.ratio))?Number(offset.ratio):1});});}catch(error){}}
function saveRadarLabelOffsets(){try{localStorage.setItem(radarOffsetStorageKey(),JSON.stringify(Object.fromEntries(radarLabelOffsets)));}catch(error){}}
function radarLabelLatLng(targetLatLng,offset){const point=radarMap.latLngToLayerPoint(targetLatLng);return radarMap.layerPointToLatLng(point.add(L.point(offset.x,offset.y)));}
function radarLabelBaseLength(){const zoom=radarMap?.getZoom()??10;if(zoom>=16)return 65;if(zoom>=13)return 85;if(zoom>=10)return 110;return 140;}
function radarDisplayOffset(offset){const source=offset||{x:-82,y:-35,ratio:1},length=Math.hypot(Number(source.x)||0,Number(source.y)||0)||1,ratio=Math.max(.55,Math.min(1.5,Number(source.ratio)||1)),displayLength=radarLabelBaseLength()*ratio;return{x:(Number(source.x)||-82)/length*displayLength,y:(Number(source.y)||-35)/length*displayLength};}
function radarLeaderEndLatLng(targetLatLng,labelLatLng){const targetPoint=radarMap.latLngToLayerPoint(targetLatLng),labelPoint=radarMap.latLngToLayerPoint(labelLatLng),dx=targetPoint.x-labelPoint.x,dy=targetPoint.y-labelPoint.y;if(Math.abs(dx)<=65&&Math.abs(dy)<=24)return targetLatLng;const xScale=Math.abs(dx)>0?65/Math.abs(dx):Infinity,yScale=Math.abs(dy)>0?24/Math.abs(dy):Infinity,scale=Math.min(xScale,yScale);return radarMap.layerPointToLatLng(L.point(labelPoint.x+dx*scale,labelPoint.y+dy*scale));}
function updateRadarLeader(target){if(!target.labelMarker||!target.leaderLine)return;const targetLatLng=target.targetMarker.getLatLng(),labelLatLng=target.labelMarker.getLatLng();target.leaderLine.setLatLngs([targetLatLng,radarLeaderEndLatLng(targetLatLng,labelLatLng)]);}
function refreshRadarTargetGeometry(){if(!radarMap)return;radarTargets.forEach(target=>{if(!target.labelMarker||!target.leaderLine)return;const offset=radarDisplayOffset(radarLabelOffsets.get(target.callsign));target.labelMarker.setLatLng(radarLabelLatLng(target.targetMarker.getLatLng(),offset));updateRadarLeader(target);});}
function radarDiamondIcon(){return L.divIcon({className:'',html:'<div class="radar-target-diamond"></div>',iconSize:[13,13],iconAnchor:[6,6]});}
function radarLabelIcon(pilot){const altitude=Math.max(0,Math.round(Number(pilot.altitude||0))),level=(altitude>=18000?'F':'A')+String(Math.round(altitude/100)).padStart(3,'0'),verticalSpeed=Number(pilot.vertical_speed||0),trend=verticalSpeed>300?'&uarr;':(verticalSpeed<-300?'&darr;':'&rarr;'),speed=String(Math.max(0,Math.round(Number(pilot.airspeed||0)))).padStart(3,'0'),squawk=String(pilot.transponder||'0000').padStart(4,'0'),route=escapeText(pilot.departure_airport||'ZZZZ')+'&rsaquo;'+escapeText(pilot.arrival_airport||'ZZZZ');return L.divIcon({className:'',html:'<div class="radar-target-label"><div class="radar-tag-row"><span>'+escapeText(pilot.callsign)+'</span><span>'+escapeText(squawk)+'</span></div><div class="radar-tag-row"><span>'+level+' '+trend+speed+'</span><span>'+escapeText(pilot.aircraft_icao||'----')+'</span></div><div class="radar-tag-route">'+route+'</div></div>',iconSize:[130,48],iconAnchor:[65,24]});}
function removeRadarTarget(callsign){const target=radarTargets.get(callsign);if(!target)return;radarTrafficLayer.removeLayer(target.targetMarker);if(target.trailLine)radarTrafficLayer.removeLayer(target.trailLine);if(target.labelMarker)radarTrafficLayer.removeLayer(target.labelMarker);if(target.leaderLine)radarTrafficLayer.removeLayer(target.leaderLine);radarTargets.delete(callsign);}
function removeRadarTargetLabel(target){if(target.labelMarker)radarTrafficLayer.removeLayer(target.labelMarker);if(target.leaderLine)radarTrafficLayer.removeLayer(target.leaderLine);target.labelMarker=null;target.leaderLine=null;}
function closeRadarContextMenu(){const menu=document.getElementById('radarContextMenu');menu.hidden=true;radarContextTarget=null;}
function positionRadarContextMenu(event,target){event.originalEvent?.preventDefault?.();event.originalEvent?.stopPropagation?.();const nativeEvent=event.originalEvent||event,touch=nativeEvent.touches?.[0]||nativeEvent.changedTouches?.[0],menu=document.getElementById('radarContextMenu');radarContextTarget=target;document.getElementById('radarContextTitle').textContent=target.callsign+' · '+String(target.pilot?.aircraft_icao||'----');menu.hidden=false;const width=235,height=145,clientX=Number(touch?.clientX??nativeEvent.clientX??0),clientY=Number(touch?.clientY??nativeEvent.clientY??0);menu.style.left=Math.max(6,Math.min(window.innerWidth-width-6,clientX))+'px';menu.style.top=Math.max(6,Math.min(window.innerHeight-height-6,clientY))+'px';}
function refreshInitialContactVisuals(){radarTargets.forEach(target=>{target.targetMarker.getElement()?.querySelector('.radar-target-diamond')?.classList.toggle('initial-contact',target.callsign===initialContactCallsign);target.labelMarker?.getElement()?.querySelector('.radar-target-label')?.classList.toggle('initial-contact',target.callsign===initialContactCallsign);});}
function attachLongPressContext(element,targetProvider){if(!element||element.dataset.atcLongPress==='1')return;element.dataset.atcLongPress='1';let timer=null,startX=0,startY=0,lastEvent=null;const cancel=()=>{if(timer)clearTimeout(timer);timer=null;};element.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;startX=event.clientX;startY=event.clientY;lastEvent=event;cancel();timer=setTimeout(()=>{timer=null;const target=targetProvider();if(target){positionRadarContextMenu(lastEvent,target);navigator.vibrate?.(25);}},650);},{passive:true});element.addEventListener('pointermove',event=>{lastEvent=event;if(Math.hypot(event.clientX-startX,event.clientY-startY)>12)cancel();},{passive:true});['pointerup','pointercancel','pointerleave'].forEach(type=>element.addEventListener(type,cancel,{passive:true}));}
function attachRadarTargetContext(target,layer){layer.on('contextmenu',event=>positionRadarContextMenu(event,target));layer.on('add',()=>setTimeout(()=>attachLongPressContext(layer.getElement?.(),()=>target),0));setTimeout(()=>attachLongPressContext(layer.getElement?.(),()=>target),0);}
function attachRadarTargetLabel(target,pilot,targetLatLng){const callsign=target.callsign,stored=radarLabelOffsets.get(callsign)||{x:-82,y:-35,ratio:1};radarLabelOffsets.set(callsign,stored);const labelLatLng=radarLabelLatLng(targetLatLng,radarDisplayOffset(stored)),labelMarker=L.marker(labelLatLng,{icon:radarLabelIcon(pilot),keyboard:false,draggable:true,autoPan:true}),leaderLine=L.polyline([],{color:'#8dff9b',weight:1.5,opacity:.95,interactive:false});target.labelMarker=labelMarker;target.leaderLine=leaderLine;leaderLine.addTo(radarTrafficLayer);labelMarker.addTo(radarTrafficLayer);attachRadarTargetContext(target,labelMarker);updateRadarLeader(target);refreshInitialContactVisuals();labelMarker.on('dragstart',()=>labelMarker.getElement()?.querySelector('.radar-target-label')?.classList.add('is-dragging'));labelMarker.on('drag',()=>updateRadarLeader(target));labelMarker.on('dragend',()=>{labelMarker.getElement()?.querySelector('.radar-target-label')?.classList.remove('is-dragging');const delta=radarMap.latLngToLayerPoint(labelMarker.getLatLng()).subtract(radarMap.latLngToLayerPoint(target.targetMarker.getLatLng())),length=Math.hypot(delta.x,delta.y)||1,ratio=Math.max(.55,Math.min(1.5,length/radarLabelBaseLength()));radarLabelOffsets.set(callsign,{x:delta.x/length,y:delta.y/length,ratio:ratio});saveRadarLabelOffsets();refreshRadarTargetGeometry();});}
function radarTrailDisplay(){const zoom=radarMap?.getZoom()??10;if(zoom>=16)return{count:12,pixels:120,weight:2,dash:'3 7',opacity:.78};if(zoom>=13)return{count:35,pixels:120,weight:2.2,dash:'3 7',opacity:.78};if(zoom>=10)return{count:90,pixels:120,weight:2.4,dash:'3 7',opacity:.80};return{count:240,pixels:120,weight:2.6,dash:'3 7',opacity:.82};}
function clipRadarTrailToPixels(positions,maxPixels){if(!radarMap||positions.length<2)return positions;const result=[positions[positions.length-1]];let remaining=maxPixels;for(let index=positions.length-2;index>=0&&remaining>0;index--){const newer=result[0],older=positions[index],newerPoint=radarMap.latLngToLayerPoint(newer),olderPoint=radarMap.latLngToLayerPoint(older),distance=newerPoint.distanceTo(olderPoint);if(distance<=remaining){result.unshift(older);remaining-=distance;continue;}if(distance>0){const ratio=remaining/distance,boundary=L.point(newerPoint.x+(olderPoint.x-newerPoint.x)*ratio,newerPoint.y+(olderPoint.y-newerPoint.y)*ratio);result.unshift(radarMap.layerPointToLatLng(boundary));}break;}return result;}
function renderRadarTrail(target){if(!target.trailLine)return;const display=radarTrailDisplay(),positions=clipRadarTrailToPixels(target.trailPositions.slice(-display.count),display.pixels);target.trailLine.setLatLngs(positions);target.trailLine.setStyle({weight:display.weight,dashArray:display.dash,opacity:display.opacity});}
function refreshRadarTrails(){radarTargets.forEach(renderRadarTrail);}
function updateRadarTrail(target,targetLatLng,pilot){const last=target.trailPositions[target.trailPositions.length-1],minimumDistance=Number(pilot.on_ground)?8:35;if(!last||last.distanceTo(targetLatLng)>=minimumDistance){target.trailPositions.push(targetLatLng);if(target.trailPositions.length>240)target.trailPositions.shift();}renderRadarTrail(target);}
function updateRadarTarget(pilot,showDetails){const callsign=String(pilot.callsign||'').trim();if(!callsign)return;const targetLatLng=L.latLng(Number(pilot.latitude),Number(pilot.longitude));let target=radarTargets.get(callsign);if(!target){const trailLine=L.polyline([],{color:'#8dff9b',weight:2,opacity:.72,dashArray:'2 8',lineCap:'round',interactive:false}),targetMarker=L.marker(targetLatLng,{icon:radarDiamondIcon(),keyboard:false,interactive:true});target={callsign,targetMarker,trailLine,trailPositions:[],labelMarker:null,leaderLine:null,pilot};trailLine.addTo(radarTrafficLayer);targetMarker.addTo(radarTrafficLayer);radarTargets.set(callsign,target);attachRadarTargetContext(target,targetMarker);}target.pilot=pilot;updateRadarTrail(target,targetLatLng,pilot);target.targetMarker.setLatLng(targetLatLng);if(!showDetails){removeRadarTargetLabel(target);refreshInitialContactVisuals();return;}if(!target.labelMarker)attachRadarTargetLabel(target,pilot,targetLatLng);target.labelMarker.setIcon(radarLabelIcon(pilot));target.labelMarker.setLatLng(radarLabelLatLng(targetLatLng,radarDisplayOffset(radarLabelOffsets.get(callsign))));updateRadarLeader(target);refreshInitialContactVisuals();const ident=Number(pilot.transponder_mode)>=4;target.targetMarker.getElement()?.querySelector('.radar-target-diamond')?.classList.toggle('ident-active',ident);target.labelMarker?.getElement()?.querySelector('.radar-target-label')?.classList.toggle('ident-active',ident);}
async function pollAtcTraffic(){try{const response=await fetch('execute/atc_traffic.php',{cache:'no-store'});const data=await response.json();if(!response.ok||!data.success)return;initializeRadarMap();loadRadarLabelOffsets();if(data.center&&currentAtcSession?.position_code!=='CTR')applyAirportRadarLimits(currentAtcSession,data.center);let traffic=Array.isArray(data.traffic)?data.traffic:[];if(currentAtcSession?.position_code==='CTR'&&radarFirLayer?.getLayers().length){const firBounds=radarFirLayer.getBounds();traffic=traffic.filter(pilot=>firBounds.contains([Number(pilot.latitude),Number(pilot.longitude)]));}const active=new Set(traffic.map(pilot=>String(pilot.callsign||'').trim()).filter(Boolean));Array.from(radarTargets.keys()).forEach(callsign=>{if(!active.has(callsign))removeRadarTarget(callsign);});const list=document.getElementById('radarTrafficList');list.innerHTML='';traffic.forEach(pilot=>{const transponderOn=Number(pilot.transponder_mode)>=2,latitude=Number(pilot.latitude),longitude=Number(pilot.longitude);updateRadarTarget(pilot,transponderOn);const row=document.createElement('button');row.type='button';row.className='traffic-row radar-traffic-jump';row.innerHTML='<strong>'+escapeText(transponderOn?pilot.callsign:'◆')+'</strong> · '+escapeText(pilot.aircraft_icao||'')+' · '+Math.round(Number(pilot.altitude||0))+' ft<span class="traffic-route">'+escapeText(pilot.pilot_name||'–')+'</span><span class="traffic-route">'+escapeText(pilot.departure_airport||'ZZZZ')+' &gt; '+escapeText(pilot.arrival_airport||'ZZZZ')+'</span>';row.addEventListener('click',()=>{if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return;const targetZoom=Math.min(radarMap.getMaxZoom(),Math.max(radarMap.getZoom(),13));radarMap.flyTo([latitude,longitude],targetZoom,{animate:true,duration:.65});});row.addEventListener('contextmenu',event=>{event.preventDefault();const target=radarTargets.get(String(pilot.callsign||'').trim());if(target)positionRadarContextMenu(event,target);});attachLongPressContext(row,()=>radarTargets.get(String(pilot.callsign||'').trim()));list.appendChild(row);});if(!traffic.length)list.innerHTML='<div class="radar-empty">–</div>';}catch(error){}}
function closeAtcFlightplan(){document.getElementById('atcFlightplanDialog').hidden=true;}
async function openAtcFlightplan(target){closeRadarContextMenu();const dialog=document.getElementById('atcFlightplanDialog'),form=document.getElementById('atcFlightplanForm'),status=document.getElementById('atcFlightplanStatus');dialog.hidden=false;form.dataset.callsign=target.callsign;document.getElementById('atcFlightplanTitle').textContent=target.callsign+' · Flugplan';status.textContent='Lade Flugplan …';try{const response=await fetch('execute/atc_flightplan_manage.php?callsign='+encodeURIComponent(target.callsign),{cache:'no-store'}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'flightplan_load_failed');for(const [name,value] of Object.entries(data.flightplan||{})){if(form.elements[name])form.elements[name].value=String(value??'');}status.textContent='';}catch(error){status.textContent=String(error.message||error);}}
document.getElementById('radarDesk').addEventListener('contextmenu',event=>event.preventDefault());
document.addEventListener('pointerdown',event=>{if(!event.target.closest('#radarContextMenu'))closeRadarContextMenu();});
document.getElementById('radarContextMenu').addEventListener('click',async event=>{const command=event.target.closest('button')?.dataset.command,target=radarContextTarget;if(!command||!target)return;if(command==='initial-contact'){closeRadarContextMenu();try{const frequency=normalizeAtcFrequency(atcChatFrequency.value||currentAtcSession?.frequency||''),body=new URLSearchParams({callsign:target.callsign,frequency}),response=await fetch('execute/atc_initial_contact.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'initial_contact_failed');initialContactCallsign=target.callsign;refreshInitialContactVisuals();}catch(error){alert(String(error.message||error));}}else if(command==='center-target'){radarMap.flyTo(target.targetMarker.getLatLng(),Math.min(radarMap.getMaxZoom(),Math.max(radarMap.getZoom(),13)),{animate:true,duration:.5});closeRadarContextMenu();}else if(command==='edit-flightplan')openAtcFlightplan(target);});
document.getElementById('atcFlightplanClose').addEventListener('click',closeAtcFlightplan);document.getElementById('atcFlightplanCancel').addEventListener('click',closeAtcFlightplan);document.getElementById('atcFlightplanDialog').addEventListener('pointerdown',event=>{if(event.target.id==='atcFlightplanDialog')closeAtcFlightplan();});
document.getElementById('atcFlightplanForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,status=document.getElementById('atcFlightplanStatus'),body=new FormData(form);body.set('callsign',form.dataset.callsign||'');status.textContent='Speichere …';try{const response=await fetch('execute/atc_flightplan_manage.php',{method:'POST',body}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'flightplan_save_failed');status.textContent='Flugplan gespeichert.';setTimeout(closeAtcFlightplan,650);pollAtcTraffic();}catch(error){status.textContent=String(error.message||error);}});
document.querySelectorAll('#atcFlightplanForm .icao-uppercase').forEach(input=>input.addEventListener('input',()=>{input.value=input.value.toUpperCase().replace(/[^A-Z0-9-]/g,'');}));
function appendAtcChatMessage(message){const id=Number(message.id||0);if(id>0&&atcChatRenderedIds.has(id))return;if(id>0)atcChatRenderedIds.add(id);const line=document.createElement('div');line.className='atc-chat-line';line.innerHTML='<span class="atc-chat-time">'+escapeText(message.time||'')+'</span><span class="atc-chat-sender">'+escapeText(message.sender||'–')+'</span><span>'+escapeText(message.text||'')+'</span>';atcChatLog.appendChild(line);while(atcChatLog.children.length>200)atcChatLog.firstElementChild?.remove();atcChatLog.scrollTop=atcChatLog.scrollHeight;}
async function pollAtcChat(reset=false){const frequency=normalizeAtcFrequency(atcChatFrequency.value);if(!frequency||atcChatRequestInFlight)return;if(reset||frequency!==atcChatFrequencyValue){atcChatFrequencyValue=frequency;atcChatSinceId=0;atcChatLog.innerHTML='';atcChatRenderedIds.clear();}atcChatRequestInFlight=true;try{const response=await fetch('execute/atc_chat.php?frequency='+encodeURIComponent(frequency)+'&since_id='+atcChatSinceId,{cache:'no-store'}),data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'chat_failed');(data.messages||[]).forEach(appendAtcChatMessage);atcChatSinceId=Math.max(atcChatSinceId,Number(data.last_id||0));}catch(error){}finally{atcChatRequestInFlight=false;}}
atcChatFrequency.addEventListener('change',()=>pollAtcChat(true));
atcChatForm.addEventListener('submit',async event=>{event.preventDefault();const frequency=normalizeAtcFrequency(atcChatFrequency.value),message=atcChatMessage.value.trim();if(!frequency||!message||atcChatSend.disabled)return;atcChatSend.disabled=true;try{const body=new URLSearchParams({frequency,message}),response=await fetch('execute/atc_chat.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body}),data=await response.json();if(!response.ok||!data.success)throw new Error(typeof data.message==='string'?data.message:'chat_send_failed');if(data.message){appendAtcChatMessage(data.message);atcChatSinceId=Math.max(atcChatSinceId,Number(data.message.id||0));}if(data.open_url)window.open(data.open_url,'_blank','noopener');atcChatMessage.value='';atcChatMessage.focus();await pollAtcChat();}catch(error){atcChatNote.hidden=false;atcChatNote.textContent=String(error.message||error);}finally{atcChatSend.disabled=false;}});
function enterRadar(session){atcPanel.__dockAtcWindow?.();atcPanel.hidden=true;const desk=document.getElementById('radarDesk');desk.hidden=false;document.getElementById('logoutAtcPositionButton').hidden=false;setSessionDisplay(session);atcChatFrequency.value=normalizeAtcFrequency(session.frequency||'')||'122.800';atcChatSend.disabled=Boolean(Number(session.is_spectator||session.spectator));atcChatMessage.disabled=atcChatSend.disabled;atcChatNote.hidden=!atcChatSend.disabled;loadRadarMaterial(session);loadAtisSettings();clearInterval(atcHeartbeatPoll);clearInterval(atcTrafficPoll);clearInterval(atcChatPoll);pollAtcHeartbeat();pollAtcTraffic();pollAtcChat(true);atcHeartbeatPoll=setInterval(pollAtcHeartbeat,5000);atcTrafficPoll=setInterval(pollAtcTraffic,3000);atcChatPoll=setInterval(pollAtcChat,2000);window.focus();}
async function logoutAtcPosition(){const button=document.getElementById('logoutAtcPositionButton');button.disabled=true;try{await setAtcPtt(false);}catch(error){}if(atcVoiceSocket){try{atcVoiceSocket.close();}catch(error){}atcVoiceSocket=null;}clearInterval(atcHeartbeatPoll);clearInterval(atcTrafficPoll);clearInterval(atcChatPoll);atcHeartbeatPoll=null;atcTrafficPoll=null;atcChatPoll=null;atcChatSinceId=0;atcChatLog.innerHTML='';try{await fetch('execute/atc_session_stop.php',{method:'POST',keepalive:true});}catch(error){}for(const popup of Array.from(detachedAtcWindows)){try{popup.close();}catch(error){}}Array.from(radarTargets.keys()).forEach(removeRadarTarget);radarLabelOffsets.clear();currentAtcSession=null;document.getElementById('radarDesk').hidden=true;button.hidden=true;button.disabled=false;atcPanel.hidden=false;atcPanel.__dockAtcWindow?.();selectedMode='';selectedPosition='';selectedStation=null;selectionArea.hidden=true;station.value='';details.hidden=true;results.hidden=true;atcPanel.querySelectorAll('.mode-button').forEach(item=>item.classList.remove('selected'));atcPanel.querySelectorAll('.position').forEach(item=>{item.classList.remove('selected','allowed');item.classList.add('locked');item.disabled=true;});update();}
function decodeAtcPcm(base64){const binary=atob(base64),samples=new Float32Array(Math.floor(binary.length/2));for(let i=0;i<samples.length;i++){let value=binary.charCodeAt(i*2)|(binary.charCodeAt(i*2+1)<<8);if(value>=32768)value-=65536;samples[i]=value/32768;}return samples;}
function encodeAtcPcm(samples){const bytes=new Uint8Array(samples.length*2),view=new DataView(bytes.buffer);for(let i=0;i<samples.length;i++){const sample=Math.max(-1,Math.min(1,samples[i]));view.setInt16(i*2,sample<0?sample*32768:sample*32767,true);}let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);}
function downsampleAtc(input,inputRate,outputRate=16000){if(outputRate>=inputRate)return new Float32Array(input);const ratio=inputRate/outputRate,result=new Float32Array(Math.max(1,Math.round(input.length/ratio)));for(let i=0;i<result.length;i++){const start=Math.floor(i*ratio),end=Math.min(input.length,Math.floor((i+1)*ratio));let sum=0,count=0;for(let j=start;j<end;j++){sum+=input[j];count++;}result[i]=count?sum/count:0;}return result;}
async function playAtcVoice(payload){if(payload.codec!=='pcm16'||typeof payload.payload!=='string')return;const samples=decodeAtcPcm(payload.payload);voicePlaybackContext=voicePlaybackContext||new(window.AudioContext||window.webkitAudioContext)();if(voicePlaybackContext.state==='suspended')await voicePlaybackContext.resume();const buffer=voicePlaybackContext.createBuffer(1,samples.length,Number(payload.sampleRate||16000));buffer.copyToChannel(samples,0);const source=voicePlaybackContext.createBufferSource();source.buffer=buffer;source.connect(voicePlaybackContext.destination);if(voicePlaybackTime<voicePlaybackContext.currentTime||voicePlaybackTime>voicePlaybackContext.currentTime+.75)voicePlaybackTime=voicePlaybackContext.currentTime+.04;source.start(voicePlaybackTime);voicePlaybackTime+=buffer.duration;}
function connectAtcVoice(){const state=document.getElementById('atcVoiceState');const frequency=normalizeAtcFrequency(document.getElementById('atcVoiceFrequency').value);const reference=document.getElementById('atcVoiceReference').value.trim().toUpperCase();document.getElementById('atcVoiceFrequency').value=frequency;if(!ATC_VOICE_TOKEN||!frequency||(frequency!=='122.800'&&!reference)){state.textContent='<?php echo addslashes(t('atc_voice_disconnected')); ?>';return;}if(atcVoiceSocket)atcVoiceSocket.close();atcVoiceSocket=new WebSocket(ATC_VOICE_URL);atcVoiceSocket.addEventListener('open',()=>atcVoiceSocket.send(JSON.stringify({type:'hello',token:ATC_VOICE_TOKEN,callsign:currentAtcSession.callsign,com1:frequency,com2:frequency,txCom:1})));atcVoiceSocket.addEventListener('message',event=>{let payload;try{payload=JSON.parse(event.data);}catch(error){return;}if(payload.type==='hello'&&payload.success){atcVoiceConnected=true;atcVoiceSocket.send(JSON.stringify({type:'monitor',frequency,global:frequency==='122.800',airportIcao:frequency==='122.800'?'':reference,rangeNm:50}));}if(payload.type==='monitor'&&payload.success)state.textContent='<?php echo addslashes(t('atc_voice_connected')); ?>'+(Number(payload.receiveOnly)?' · <?php echo addslashes(t('atc_voice_receive_only')); ?>':'');if(payload.type==='audio')playAtcVoice(payload).catch(()=>{});if(payload.type==='error')state.textContent=String(payload.message||'Voice error');});atcVoiceSocket.addEventListener('close',()=>{atcVoiceConnected=false;state.textContent='<?php echo addslashes(t('atc_voice_disconnected')); ?>';});}
async function setAtcPtt(active){if(Number(currentAtcSession?.is_spectator||currentAtcSession?.spectator))return;if(!atcVoiceConnected)connectAtcVoice();if(active){atcMicStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true},video:false});atcMicContext=atcMicContext||new(window.AudioContext||window.webkitAudioContext)();await atcMicContext.resume();atcMicSource=atcMicContext.createMediaStreamSource(atcMicStream);atcMicProcessor=atcMicContext.createScriptProcessor(2048,1,1);atcMicGain=atcMicContext.createGain();atcMicGain.gain.value=0;atcMicProcessor.onaudioprocess=event=>{if(!atcVoiceConnected)return;const frequency=document.getElementById('atcVoiceFrequency').value.trim();atcVoiceSocket.send(JSON.stringify({type:'audio',codec:'pcm16',sampleRate:16000,frequency,sequence:++atcVoiceSequence,ptt:true,payload:encodeAtcPcm(downsampleAtc(event.inputBuffer.getChannelData(0),atcMicContext.sampleRate))}));};atcMicSource.connect(atcMicProcessor);atcMicProcessor.connect(atcMicGain);atcMicGain.connect(atcMicContext.destination);atcVoiceSocket?.send(JSON.stringify({type:'ptt',active:true,txCom:1,frequency:document.getElementById('atcVoiceFrequency').value.trim()}));}else{atcVoiceSocket?.send(JSON.stringify({type:'ptt',active:false,txCom:1,frequency:document.getElementById('atcVoiceFrequency').value.trim()}));if(atcMicProcessor){atcMicProcessor.disconnect();atcMicProcessor=null;}if(atcMicSource){atcMicSource.disconnect();atcMicSource=null;}if(atcMicStream){atcMicStream.getTracks().forEach(track=>track.stop());atcMicStream=null;}}}
document.getElementById('atcVoiceConnect').addEventListener('click',connectAtcVoice);
document.getElementById('atcVoiceFrequency').addEventListener('blur',function(){this.value=normalizeAtcFrequency(this.value);});
document.getElementById('atcVoiceFrequency').addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();connectAtcVoice();}});
document.getElementById('atcAtisForm').addEventListener('submit',event=>{event.preventDefault();saveAtisSettings('save');});
document.getElementById('atcAtisAutomatic').addEventListener('click',()=>saveAtisSettings('automatic'));
const atcPttButton=document.getElementById('atcVoicePtt');atcPttButton.addEventListener('pointerdown',()=>setAtcPtt(true).catch(()=>{}));['pointerup','pointercancel','pointerleave'].forEach(type=>atcPttButton.addEventListener(type,()=>setAtcPtt(false).catch(()=>{})));
function update(){next.disabled=!selectedPosition||!selectedStation;}
function escapeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function chooseStation(item){selectedStation=item;station.value=item.code;results.hidden=true;details.hidden=false;details.innerHTML='<strong>'+escapeText(item.code)+'</strong> · '+escapeText(item.name)+(item.municipality?' · '+escapeText(item.municipality):'')+'<br><small>'+escapeText(item.kind_label)+(item.operation_label?' · '+escapeText(item.operation_label):'')+'</small>';const eligible=Array.isArray(item.eligible_positions)?item.eligible_positions:[];atcPanel.querySelectorAll('.position').forEach(button=>{const rankAllowed=selectedMode==='spectator'||button.dataset.rankAllowed==='1';const usable=rankAllowed&&eligible.includes(button.dataset.code);button.disabled=!usable;button.classList.toggle('allowed',usable);button.classList.toggle('locked',!usable);if(!usable&&button.classList.contains('selected')){button.classList.remove('selected');selectedPosition='';}});update();station.focus();}
async function searchStations(){const query=station.value.trim();const sequence=++searchSequence;if(searchController)searchController.abort();searchController=new AbortController();selectedStation=null;details.hidden=true;update();if(query.length<2){results.hidden=true;return;}try{const response=await fetch('execute/atc_station_search.php?q='+encodeURIComponent(query)+'&spectator='+(selectedMode==='spectator'?'1':'0'),{signal:searchController.signal});const data=await response.json();if(sequence!==searchSequence)return;if(!response.ok||!data.success)throw new Error(data.message||'search_failed');const items=Array.isArray(data.items)?data.items:[];const exact=items.find(item=>String(item.code).toUpperCase()===query.toUpperCase());if(exact&&items.length===1){chooseStation(exact);return;}results.innerHTML='';items.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='station-result';button.innerHTML='<strong>'+escapeText(item.code)+'</strong> · '+escapeText(item.name)+'<small>'+escapeText(item.municipality||'')+' · '+escapeText(item.kind_label)+'</small>';button.addEventListener('mousedown',event=>{event.preventDefault();chooseStation(item);});results.appendChild(button);});if(items.length===0){results.innerHTML='<div class="station-result"><?php echo addslashes(t('atc_station_no_results')); ?></div>';}results.hidden=false;}catch(error){if(error.name==='AbortError'||sequence!==searchSequence)return;results.innerHTML='<div class="station-result"><?php echo addslashes(t('atc_station_search_error')); ?></div>';results.hidden=false;}}
function chooseMode(mode,button){selectedMode=mode;if(searchController)searchController.abort();++searchSequence;atcPanel.querySelectorAll('.mode-button').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');atcPanel.querySelectorAll('.supervision-note').forEach(item=>item.hidden=mode==='spectator');selectionArea.hidden=false;selectedPosition='';selectedStation=null;station.value='';details.hidden=true;results.hidden=true;atcPanel.querySelectorAll('.position').forEach(item=>{item.classList.remove('selected','allowed');item.classList.add('locked');item.disabled=true;});update();station.focus();}
document.getElementById('controllerMode')?.addEventListener('click',function(){chooseMode('controller',this);});
document.getElementById('spectatorMode').addEventListener('click',function(){chooseMode('spectator',this);});
station.addEventListener('input',function(){clearTimeout(searchTimer);searchTimer=setTimeout(searchStations,180);});
station.addEventListener('keydown',function(event){if(event.key==='Escape')results.hidden=true;if(event.key==='Enter'){event.preventDefault();const first=results.querySelector('button.station-result');if(first)first.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));}});
atcPanel.querySelectorAll('.position').forEach(button=>button.addEventListener('click',function(){if(this.disabled)return;atcPanel.querySelectorAll('.position').forEach(item=>item.classList.remove('selected'));this.classList.add('selected');selectedPosition=this.dataset.code;update();}));
next.addEventListener('click',async function(){next.disabled=true;try{const body=new URLSearchParams({station:selectedStation.code,position:selectedPosition,spectator:selectedMode==='spectator'?'1':'0'});const response=await fetch('execute/atc_session_start.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'session_failed');selectionHint.textContent=data.callsign+' – '+(data.spectator?'<?php echo addslashes(t('atc_spectator_ready')); ?>':'<?php echo addslashes(t('atc_position_ready')); ?>');enterRadar(data);}catch(error){selectionHint.textContent=error.message;}finally{update();}});
async function resumeAtcSession(){try{const response=await fetch('execute/atc_heartbeat.php',{cache:'no-store'});if(!response.ok)return;const data=await response.json();if(data.success&&data.session)enterRadar(data.session);}catch(error){}}
resumeAtcSession();
document.getElementById('logoutAtcPositionButton').addEventListener('click',logoutAtcPosition);
<?php endif; ?>
}
</script>
</body></html>
