<?php
require_once __DIR__.'/includes/session_bootstrap.php';startVfnWebSession();
require_once __DIR__.'/execute/config.php';require_once __DIR__.'/includes/language.php';
$countries=require __DIR__.'/includes/countries.php';
$days=(int)($_GET['days']??30);if(!in_array($days,[0,1,7,30,90,365],true))$days=30;
$ownUserId=max(0,(int)($_SESSION['web_user_id']??0));$userId=max(0,(int)($_GET['user_id']??0));$requestedMode=(string)($_GET['mode']??'global');
$mode=$requestedMode==='own'&&$ownUserId>0?'own':(($requestedMode==='player'||$userId>0)?'player':'global');if($mode==='own')$userId=$ownUserId;
?>
<!doctype html><html lang="<?php echo htmlspecialchars($currentLanguage); ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo htmlspecialchars(t('statistics_title')); ?> - <?php echo htmlspecialchars($projectName); ?></title>
<style>
body{margin:0;background:radial-gradient(circle at 20% 10%,rgba(0,132,255,.18),transparent 32%),#07141f;color:#d7e8ff;font-family:Arial,sans-serif}.shell{width:min(1500px,calc(100% - 36px));margin:34px auto}.hero{display:flex;justify-content:space-between;align-items:end;gap:20px}.controls,.mode-switch,.sort-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.period,.player-search{padding:10px;background:#071521;color:white;border:1px solid #285475;border-radius:5px}.mode-button{padding:11px 18px;border:1px solid #285475;background:#0d1d2a;color:#d7e8ff;border-radius:5px;cursor:pointer}.mode-button.active{background:#176dcc;border-color:#55aaff;color:white}.player-picker{position:relative;margin:15px 0}.player-search{width:min(440px,100%);box-sizing:border-box}.search-results{position:absolute;z-index:20;width:min(440px,100%);background:#071521;border:1px solid #285475;box-shadow:0 12px 30px #000}.search-results:empty{display:none}.search-result{display:block;width:100%;padding:11px;border:0;border-bottom:1px solid #18364b;background:transparent;color:#d7e8ff;text-align:left;cursor:pointer}.search-result:hover{background:#123452}.selected-player{color:#55e9c1;font-weight:bold;margin-left:10px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:22px 0}.stat,.card{background:#0d1d2a;border:1px solid #285475;border-radius:8px;padding:18px}.stat strong{display:block;color:#55e9c1;font-size:28px}.columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.ranking{display:grid;gap:9px}.rank{display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center;padding:11px;background:#081925;border-radius:5px}.number{font-size:20px;color:#55aaff;font-weight:bold}.meta{color:#93acc3;font-size:12px;margin-top:3px}.flag{width:22px;height:15px;object-fit:cover;vertical-align:-2px;margin-right:7px}.pilot-name{color:#65bdff;text-decoration:none;font-weight:bold}.wide-card{margin-top:18px}.card-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.map-link{display:inline-block;color:white;background:#176dcc;padding:10px 14px;border-radius:5px;text-decoration:none}.online-dot-small{display:inline-block;width:9px;height:9px;border-radius:50%;background:#36c64b;margin-left:6px;box-shadow:0 0 7px #36c64b}.live-link{color:#55e9c1;text-decoration:none;font-size:12px}@media(max-width:1050px){.columns{grid-template-columns:1fr}}@media(max-width:800px){.summary{grid-template-columns:1fr 1fr}.hero,.card-head{align-items:start;flex-direction:column}}
.atc-summary{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin:15px 0 20px}.atc-summary .stat{padding:13px}.atc-summary .stat strong{font-size:22px}.country-details{background:#081925;border-radius:5px;overflow:hidden}.country-details summary{position:relative;cursor:pointer;list-style:none}.country-details summary::-webkit-details-marker{display:none}.country-details summary:after{content:'▸';position:absolute;right:10px;top:50%;color:#55aaff;transform:translateY(-50%)}.country-details[open] summary:after{content:'▾'}.country-details .rank{border-radius:0;padding-right:28px}.country-airports{display:grid;gap:1px;padding:0 11px 11px 53px}.country-airport{display:grid;grid-template-columns:32px minmax(0,1fr) auto;gap:8px;align-items:center;padding:8px 0;border-top:1px solid #18364b}.country-airport .number{font-size:14px}.country-airport strong:last-child{white-space:nowrap;font-size:13px}@media(max-width:1200px){.atc-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.atc-summary{grid-template-columns:1fr 1fr}.country-airports{padding-left:18px}}
</style></head><body><?php require __DIR__.'/includes/header.php'; ?>
<main class="shell"><section class="hero"><div><h1><?php echo htmlspecialchars(t('statistics_title')); ?></h1><p><?php echo htmlspecialchars(t('statistics_text')); ?></p></div><select class="period" id="period"><?php foreach([1,7,30,90,365,0] as $v): ?><option value="<?php echo $v; ?>" <?php echo $days===$v?'selected':''; ?>><?php echo htmlspecialchars(t('statistics_period_'.$v)); ?></option><?php endforeach; ?></select></section>
<div class="mode-switch"><button class="mode-button <?php echo $mode==='global'?'active':''; ?>" data-mode="global"><?php echo htmlspecialchars(t('statistics_global')); ?></button><?php if($ownUserId>0): ?><button class="mode-button <?php echo $mode==='own'?'active':''; ?>" data-mode="own"><?php echo htmlspecialchars(t('statistics_own')); ?></button><?php endif; ?><button class="mode-button <?php echo $mode==='player'?'active':''; ?>" data-mode="player"><?php echo htmlspecialchars(t('statistics_search_mode')); ?></button></div>
<div class="player-picker" id="playerPicker" <?php echo $mode!=='player'?'hidden':''; ?>><input class="player-search" id="playerSearch" placeholder="<?php echo htmlspecialchars(t('statistics_search_player')); ?>" autocomplete="off"><span class="selected-player" id="selectedPlayer"></span><div class="search-results" id="playerResults"></div></div>
<div id="statisticsLoading"><?php echo htmlspecialchars(t('statistics_loading')); ?></div><section id="statisticsContent" hidden>
<div class="summary"><div class="stat"><strong id="sumFlights">0</strong><?php echo htmlspecialchars(t('statistics_flights')); ?></div><div class="stat"><strong id="sumPilots">0</strong><?php echo htmlspecialchars(t('statistics_pilots')); ?></div><div class="stat"><strong id="sumDistance">0</strong><?php echo htmlspecialchars(t('statistics_distance')); ?></div><div class="stat"><strong id="sumHours">0</strong><?php echo htmlspecialchars(t('statistics_hours')); ?></div></div>
<div class="columns"><section class="card" id="aircraftStatistics"><div class="card-head"><h2><?php echo htmlspecialchars(t('statistics_top_aircraft')); ?></h2><select class="period" id="aircraftSort"><option value="flights"><?php echo htmlspecialchars(t('statistics_sort_flights')); ?></option><option value="distance"><?php echo htmlspecialchars(t('statistics_sort_distance')); ?></option><option value="hours"><?php echo htmlspecialchars(t('statistics_sort_hours')); ?></option><option value="airports"><?php echo htmlspecialchars(t('statistics_sort_airports')); ?></option></select></div><div class="ranking" id="topAircraft"></div></section><section class="card" id="airportStatistics"><h2><?php echo htmlspecialchars(t('statistics_top_airports')); ?></h2><div class="ranking" id="topAirports"></div></section><section class="card" id="countryStatistics"><h2 id="countryTitle"><?php echo htmlspecialchars(t('statistics_top_movement_countries')); ?></h2><div class="ranking" id="topCountries"></div></section></div>
<section class="card wide-card" id="pilotCard"><div class="card-head"><h2><?php echo htmlspecialchars(t('statistics_top_pilots')); ?></h2><select class="period" id="pilotSort"><option value="flights"><?php echo htmlspecialchars(t('statistics_sort_flights')); ?></option><option value="distance"><?php echo htmlspecialchars(t('statistics_sort_distance')); ?></option><option value="hours"><?php echo htmlspecialchars(t('statistics_sort_hours')); ?></option><option value="landings"><?php echo htmlspecialchars(t('statistics_sort_landings')); ?></option></select></div><div class="ranking" id="topPilots"></div></section>
<section class="card wide-card" id="atcStatistics"><div class="card-head"><h2><?php echo htmlspecialchars(t('statistics_atc')); ?></h2><select class="period" id="atcSort"><option value="hours"><?php echo htmlspecialchars(t('statistics_sort_hours')); ?></option><option value="sessions"><?php echo htmlspecialchars(t('statistics_sort_sessions')); ?></option><option value="average"><?php echo htmlspecialchars(t('statistics_sort_average_session')); ?></option></select></div><div class="atc-summary"><div class="stat"><strong id="sumAtcSessions">0</strong><?php echo htmlspecialchars(t('statistics_atc_sessions')); ?></div><div class="stat"><strong id="sumAtcHours">0</strong><?php echo htmlspecialchars(t('statistics_controller_hours')); ?></div><div class="stat"><strong id="sumAtcControllers">0</strong><?php echo htmlspecialchars(t('statistics_atc_controllers')); ?></div><div class="stat"><strong id="sumAtcPositions">0</strong><?php echo htmlspecialchars(t('statistics_atc_positions')); ?></div><div class="stat"><strong id="sumAtcStations">0</strong><?php echo htmlspecialchars(t('statistics_atc_stations')); ?></div><div class="stat"><strong id="avgAtcSession">0</strong><?php echo htmlspecialchars(t('statistics_average_session')); ?></div></div><div class="columns"><div><h3><?php echo htmlspecialchars(t('statistics_top_atc_positions')); ?></h3><div class="ranking" id="topAtcPositions"></div></div><div id="topControllersWrap"><h3><?php echo htmlspecialchars(t('statistics_top_controllers')); ?></h3><div class="ranking" id="topControllers"></div></div></div></section>
<p id="heatmapLink"><a class="map-link" href="map.php?heatmap=1&days=<?php echo $days; ?>"><?php echo htmlspecialchars(t('statistics_open_heatmap')); ?></a></p></section></main>
<?php require __DIR__.'/includes/footer.php';require __DIR__.'/includes/auth_modals.php'; ?>
<script>
const COUNTRY_NAMES=<?php echo json_encode($countries,JSON_UNESCAPED_UNICODE); ?>,TXT=<?php echo json_encode(['movements'=>t('statistics_movements'),'flights'=>t('statistics_flights'),'pilots'=>t('statistics_pilots'),'airports'=>t('statistics_airports'),'landings'=>t('statistics_landings'),'live'=>t('statistics_view_live'),'empty'=>t('statistics_empty')],JSON_UNESCAPED_UNICODE); ?>;
const ownUserId=<?php echo $ownUserId; ?>;let mode=<?php echo json_encode($mode); ?>,userId=<?php echo $userId; ?>,searchTimer;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function metric(v,sort){if(sort==='distance')return Number(v.distance_nm||0).toLocaleString()+' NM';if(sort==='hours')return (Number(v.duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})+' h';if(sort==='airports')return Number(v.airports||0)+' '+TXT.airports;if(sort==='landings')return Number(v.landings||0)+' '+TXT.landings;return Number(v.flights||0)+' '+TXT.flights}
function empty(){return `<p>${esc(TXT.empty)}</p>`}function flag(code){return code&&code!=='--'?`<img class="flag" src="images/flags/${esc(code.toLowerCase())}.png" alt="">`:''}
function loadStatistics(){if(mode==='player'&&!userId){document.getElementById('statisticsContent').hidden=true;document.getElementById('statisticsLoading').hidden=false;document.getElementById('statisticsLoading').textContent=<?php echo json_encode(t('statistics_select_player')); ?>;return}const days=document.getElementById('period').value,aSort=document.getElementById('aircraftSort').value,pSort=document.getElementById('pilotSort').value,atcOrder=document.getElementById('atcSort').value;document.getElementById('statisticsLoading').hidden=false;document.getElementById('statisticsLoading').textContent=<?php echo json_encode(t('statistics_loading')); ?>;fetch(`execute/network_statistics.php?days=${days}&user_id=${mode==='global'?0:userId}&aircraft_sort=${aSort}&pilot_sort=${pSort}&atc_sort=${atcOrder}`).then(r=>r.json()).then(data=>{if(!data.success)throw new Error();const s=data.summary||{};sumFlights.textContent=s.flights||0;sumPilots.textContent=mode==='global'?(s.pilots||0):'1';sumDistance.textContent=Number(s.distance_nm||0).toLocaleString()+' NM';sumHours.textContent=(Number(s.duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})+' h';if(data.user)selectedPlayer.textContent=(data.user.real_name?data.user.real_name+' · ':'')+data.user.username;
const aircraft=data.top_aircraft||[];topAircraft.innerHTML=aircraft.length?aircraft.map((a,i)=>`<div class="rank"><span class="number">${i+1}</span><div><strong>${esc(a.code)}</strong><div class="meta">${a.flights} ${esc(TXT.flights)} · ${Number(a.distance_nm).toLocaleString()} NM · ${(Number(a.duration_seconds)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h · ${a.airports} ${esc(TXT.airports)}</div></div><strong>${esc(metric(a,aSort))}</strong></div>`).join(''):empty();
const airports=data.top_airports||[];topAirports.innerHTML=airports.length?airports.map((a,i)=>`<div class="rank"><span class="number">${i+1}</span><div><a class="pilot-name" href="airport.php?icao=${encodeURIComponent(a.code)}">${esc(a.code)}</a><div class="meta">${esc(a.name||'')} ${esc(a.municipality||'')}</div></div><strong>${a.movements} ${esc(TXT.movements)}</strong></div>`).join(''):empty();
const countries=data.top_movement_countries||[];topCountries.innerHTML=countries.length?countries.map((c,i)=>{const countryAirports=Array.isArray(c.airport_details)?c.airport_details:[],details=countryAirports.length?`<div class="country-airports">${countryAirports.map((a,j)=>`<div class="country-airport"><span class="number">${j+1}</span><div><a class="pilot-name" href="airport.php?icao=${encodeURIComponent(a.code)}">${esc(a.code)}</a><div class="meta">${esc(a.name||'')}${a.name&&a.municipality?' · ':''}${esc(a.municipality||'')}</div></div><strong>${Number(a.movements||0).toLocaleString()} ${esc(TXT.movements)}</strong></div>`).join('')}</div>`:'';return `<details class="country-details"><summary><div class="rank"><span class="number">${i+1}</span><div><strong>${flag(c.code)}${esc(COUNTRY_NAMES[c.code]||c.code)}</strong><div class="meta">${c.airports} ${esc(TXT.airports)}</div></div><strong>${c.movements} ${esc(TXT.movements)}</strong></div></summary>${details}</details>`}).join(''):empty();
const pilots=data.top_pilots||[];topPilots.innerHTML=pilots.length?pilots.map((p,i)=>{const name=p.real_name?`${p.real_name} (${p.username})`:p.username,live=p.online?`<span class="online-dot-small"></span> <a class="live-link" href="map.php?pilot_id=${p.user_id}&follow=1">${esc(TXT.live)}</a>`:'';return `<div class="rank"><span class="number">${i+1}</span><div>${flag(p.country_code)}<a class="pilot-name" href="profile.php?id=${p.user_id}">${esc(name)}</a><div class="meta">${p.flights} ${esc(TXT.flights)} · ${Number(p.distance_nm).toLocaleString()} NM · ${(Number(p.duration_seconds)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h ${live}</div></div><strong>${esc(metric(p,pSort))}</strong></div>`}).join(''):empty();renderAtc(data);pilotCard.hidden=mode!=='global';heatmapLink.hidden=mode!=='global';statisticsLoading.hidden=true;statisticsContent.hidden=false;history.replaceState(null,'',`statistics.php?mode=${mode}&days=${days}${mode==='player'?'&user_id='+userId:''}${location.hash}`)}).catch(()=>statisticsLoading.textContent='Server error')}
document.querySelectorAll('.mode-button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode-button').forEach(x=>x.classList.toggle('active',x===b));playerPicker.hidden=mode!=='player';if(mode==='global')userId=0;else if(mode==='own')userId=ownUserId;else{userId=0;selectedPlayer.textContent=''}loadStatistics()});period.onchange=loadStatistics;aircraftSort.onchange=loadStatistics;pilotSort.onchange=loadStatistics;atcSort.onchange=loadStatistics;
playerSearch.oninput=()=>{clearTimeout(searchTimer);const q=playerSearch.value.trim();if(q.length<2){playerResults.innerHTML='';return}searchTimer=setTimeout(()=>fetch('execute/statistics_player_search.php?q='+encodeURIComponent(q)).then(r=>r.json()).then(d=>{playerResults.innerHTML=(d.players||[]).map(p=>`<button class="search-result" data-id="${p.id}" data-name="${esc(p.real_name||p.username)}">${flag(p.country_code)}${esc(p.real_name||p.username)} · ${esc(p.username)}</button>`).join('');playerResults.querySelectorAll('button').forEach(b=>b.onclick=()=>{userId=Number(b.dataset.id);selectedPlayer.textContent=b.dataset.name;playerSearch.value='';playerResults.innerHTML='';loadStatistics()})}),250)};
function renderAtc(data){const summary=data.atc_summary||{},positions=data.top_atc_positions||[],controllers=data.top_controllers||[],sort=atcSort.value;sumAtcSessions.textContent=Number(summary.sessions||0).toLocaleString();sumAtcHours.textContent=(Number(summary.duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})+' h';sumAtcControllers.textContent=Number(summary.controllers||0).toLocaleString();sumAtcPositions.textContent=Number(summary.positions||0).toLocaleString();sumAtcStations.textContent=Number(summary.stations||0).toLocaleString();avgAtcSession.textContent=(Number(summary.average_duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})+' h';const atcMetric=p=>sort==='sessions'?`${Number(p.sessions||0).toLocaleString()} <?php echo addslashes(t('statistics_atc_sessions')); ?>`:sort==='average'?`Ø ${(Number(p.average_duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h`:`${(Number(p.duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h`;const atcMeta=p=>`${Number(p.sessions||0).toLocaleString()} <?php echo addslashes(t('statistics_atc_sessions')); ?> · ${(Number(p.duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h · Ø ${(Number(p.average_duration_seconds||0)/3600).toLocaleString(undefined,{maximumFractionDigits:1})} h`;topAtcPositions.innerHTML=positions.length?positions.map((p,i)=>`<div class="rank"><span class="number">${i+1}</span><div><strong>${esc(p.callsign)}</strong><div class="meta">${atcMeta(p)}</div></div><strong>${atcMetric(p)}</strong></div>`).join(''):empty();topControllers.innerHTML=controllers.length?controllers.map((p,i)=>`<div class="rank"><span class="number">${i+1}</span><div>${flag(p.country_code)}<a class="pilot-name" href="profile.php?id=${p.user_id}">${esc(p.real_name||p.username)}</a><div class="meta">${atcMeta(p)}</div></div><strong>${atcMetric(p)}</strong></div>`).join(''):empty();topControllersWrap.hidden=mode!=='global'}
loadStatistics();if(location.hash==='#aircraftStatistics')setTimeout(()=>document.getElementById('aircraftStatistics').scrollIntoView({behavior:'smooth'}),250);
</script></body></html>
