<?php
declare(strict_types=1);

/** Combine cached per-airport Gateway apt.dat payloads into one import file. */
$root = dirname(__DIR__);
$options = getopt('', ['cache::', 'output::']);
$cache = rtrim((string)($options['cache'] ?? ($root . '/data-sources/xplane-gateway/apt')), "\\/");
$output = (string)($options['output'] ?? ($root . '/data-sources/xplane-gateway/gateway-airports.dat'));
if (!is_dir($cache)) { throw new RuntimeException('Gateway cache not found: ' . $cache); }
$temporary = $output . '.tmp-' . getmypid();
$handle = fopen($temporary, 'wb');
if ($handle === false) { throw new RuntimeException('Cannot create catalog: ' . $temporary); }
fwrite($handle, "I\n1200 Generated by VFN from recommended X-Plane Gateway apt.dat payloads\n\n");
$files = glob($cache . DIRECTORY_SEPARATOR . '*.dat') ?: [];
sort($files, SORT_NATURAL | SORT_FLAG_CASE);
$count = 0;
foreach ($files as $file) {
    $payload = (string)file_get_contents($file);
    $lines = preg_split('/\R/', $payload) ?: [];
    foreach ($lines as $line) {
        $trimmed = trim($line);
        // Every per-airport payload is a complete apt.dat file and therefore
        // carries its own EOF record.  A combined catalogue may contain that
        // marker only once, otherwise the streaming importer stops after the
        // first airport.
        if ($trimmed === '' || $trimmed === 'I' || $trimmed === '99' || preg_match('/^\d+\s+Generated by/', $trimmed)) { continue; }
        fwrite($handle, $line . "\n");
    }
    fwrite($handle, "\n");
    $count++;
}
fwrite($handle, "99\n");
fclose($handle);
if (!rename($temporary, $output)) { @unlink($temporary); throw new RuntimeException('Cannot publish catalog.'); }
fwrite(STDOUT, json_encode(['airports' => $count, 'output' => $output, 'bytes' => filesize($output)], JSON_UNESCAPED_SLASHES) . PHP_EOL);
